// Generated by just contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


export type RawJSON = string & { readonly __rawJSON: unique symbol };

export type PresentationBlock = RawJSON;

export type BrokerPermission = "artifact_read" | "artifact_write" | "remote_tools";

export type ConflictState = { conversation: Conversation; type: "conversation" } | { run: Run; type: "run" };

export type Conversation = { conversation_id: string; created_at_unix_ms: number; name?: Name | null; origin?: ConversationOrigin | null; retention: RetentionPolicy; revision?: string | null; working_tree?: WorkingTree | null };

export type ConversationOrigin = { kind: "new" } | { import_id: string; kind: "imported" } | { checkpoint_turn: number; kind: "forked"; source_conversation_id: string; source_run_id: string };

export type CraftAction = { action_id: string; input: RawJSON; kind: "invoke" } | { decision: CraftApprovalDecision; kind: "approval"; request_id: string };

export type CraftApprovalDecision = "allow_once" | "deny";

export type CraftApprovalRequest = { action: string; request_id: string; tool: string };

export type CraftCommand = { kind: "configure_remote_tools"; selection: NoVisaSelection } | { kind: "remote_tool_result"; operation_id: string; outcome: RemoteToolOutcome } | { checkpoint: string; helper_socket: string; id: string; kind: "recover"; source_offset: number } | { helper_socket: string; id: string; kind: "start"; text: string } | { kind: "acknowledge"; source_offset: number } | { id: string; kind: "turn"; text: string } | { id: string; kind: "interrupt" } | { action: CraftAction; id: string; kind: "action" } | { kind: "shutdown" };

export type CraftEvent = { call: CraftRemoteTool; kind: "remote_tool" } | { kind: "usage"; usage: CraftUsage } | { kind: "approval_requested"; request: CraftApprovalRequest } | { kind: "turn_started" } | { kind: "turn_ended"; outcome: TurnOutcome } | { change: CraftFileChange; kind: "file_changed" } | { kind: "conversation_title"; title: string } | { kind: "run_title"; title: string } | { kind: "process_title"; pid: number; title: string } | { kind: "run_launch_failed" } | { harness_pid: number; helper_pid: number; kind: "run_started" } | { activity: RunActivity; kind: "activity" } | { checkpoint?: string; kind: "progress"; source_offset: number } | { helper_pid: number; kind: "run_recovered"; source_offset: number } | { exit_code?: number | null; kind: "run_ended" } | { kind: "output"; native_event: RawJSON; presentation?: Array<PresentationBlock> } | { id: string; kind: "completed"; native_conversation: string };

export type CraftExtensionReply = { catalog: ExtensionCatalog; kind: "catalog" } | { kind: "applied" } | { kind: "refused" };

export type CraftExtensionRequest = { kind: "catalog" } | { extension_id: string; kind: "inspect" } | { confirmation: ExtensionConfirmation; kind: "apply" };

export type CraftFeature = { name: string; required?: boolean };

export type CraftFileChange = { activity_id: string; after_mode: string; after_object: string; before_mode: string; before_object: string; path: string };

export type CraftFork = { checkpoint_commit: string; checkpoint_tree: string; checkpoint_turn: number; source_conversation_id: string; source_native_conversation: string; source_run_id: string };

export type CraftHello = { execution_id: string; fork?: CraftFork | null; protocol: ProtocolOffer; resume?: CraftResume | null; specification: ProtocolOffer };

export type CraftHostAccess = { kind: "executable"; name: string } | { kind: "filesystem"; path: string } | { kind: "environment"; name: string } | { destination: string; kind: "network" };

export type CraftObservedUsage = { estimation: CraftUsageEstimation; finality: CraftUsageFinality; measurement: CraftUsageMeasurement; model?: string | null; tokens: CraftUsageTokens };

export type CraftQuotaScope = { covers: "provider_account" } | { covers: "model"; model: string };

export type CraftQuotaUnit = "tokens" | "requests" | "credits" | "share";

export type CraftQuotaWindow = { estimation: CraftUsageEstimation; finality: CraftUsageFinality; limit?: number | null; resets_in_seconds?: number | null; scope: CraftQuotaScope; unit: CraftQuotaUnit; used: number; window: string; window_seconds?: number | null };

export type CraftReady = { enabled_features: Array<string>; protocol: NegotiatedProtocol; specification: CraftSpecification; specification_protocol: NegotiatedProtocol };

export type CraftRemoteTool = { action: RemoteToolAction; destination_plane_id: string; operation_id: string; workspace_id: string };

export type CraftResume = { native_conversation: string; version: ProtocolVersion };

export type CraftReviewInput = { action: string; tool: string; transcript: string };

export type CraftReviewModel = { model: string; reviewer: CraftReviewer; version: number };

export type CraftReviewReply = { model: string; output: string; reviewer: CraftReviewer; version: number };

export type CraftReviewRequest = { binding_id: string; credential_reference: CredentialReference; input: CraftReviewInput; model: string; version: number };

export type CraftReviewer = "native" | "equivalent";

export type CraftSpecification = { broker_permissions?: Array<BrokerPermission>; features?: Array<CraftFeature>; harness: string; host_access?: Array<CraftHostAccess>; id: string; protocol: ProtocolOffer; schema: ProtocolVersion };

export type CraftUsage = { observed: CraftObservedUsage; source: "observed" } | { quota: CraftQuotaWindow; source: "quota" } | { reason: string; source: "unreachable" };

export type CraftUsageEstimation = "measured" | "estimated";

export type CraftUsageFinality = "interim" | "final";

export type CraftUsageMeasurement = { covers: "turn"; native_usage_id?: string | null; turn: string } | { covers: "run"; native_usage_id?: string | null };

export type CraftUsageTokens = { cached_input?: number; input?: number; output?: number; reasoning?: number };

export type CraftUtilityModel = { model: string; version: number };

export type CraftUtilityReply = { model: string; output: string; version: number };

export type CraftUtilityRequest = { binding_id: string; credential_reference: CredentialReference; input: UtilityInput; model: string; version: number };

export type CredentialItem = { account: string; service: string };

export type CredentialReference = { item: CredentialItem; source: "platform_store" } | { helper: string; source: "external_helper" } | { source: "harness_native" } | { established_at_daemon_start: number; source: "session_only" };

export type ErrorCategory = "invalid_input" | "unauthorized" | "conflict" | "unavailable" | "incompatible" | "rate_limited" | "not_found" | "outcome_unknown" | "internal";

export type ExtensionAction = "install" | "update" | "disable" | "remove";

export type ExtensionCatalog = { craft_id: string; harness: string; native_metadata: string };

export type ExtensionConfirmation = { action: ExtensionAction; catalog: ExtensionCatalog; extension_id: string; scope: ExtensionScope; trust: ExtensionTrust };

export type ExtensionScope = "user";

export type ExtensionTrust = "same_user_executable";

export type FileRevision = { mode: string; object: string };

export type FileTarget = { kind: "project"; project_id: string } | { kind: "workspace"; workspace_id: string };

export type Name = { source: NameSource; value: string };

export type NameSource = "manual" | "utility" | "harness_native" | "deterministic";

export type NegotiatedProtocol = { capabilities: Array<string>; family: ProtocolFamily; version: ProtocolVersion };

export type NoVisaDestination = { plane_id: string; ssh_endpoint: string; workspace_id: string };

export type NoVisaSelection = { account_binding_id: string; conversation_id: string; destinations: Array<NoVisaDestination>; jet_equivalent: Array<string>; native_unavailable: Array<string>; origin_plane_id: string };

export type Presentation = { kind: "text"; text: string } | { kind: "markdown"; text: string } | { actions: Array<PresentationAction>; kind: "actions" };

export type PresentationAction = { id: string; label: string };

export type ProtocolFamily = "client" | "craft" | "helper" | "specification";

export type ProtocolOffer = { capabilities?: Array<string>; family: ProtocolFamily; versions: Array<ProtocolVersion> };

export type ProtocolVersion = { major: number; minor: number };

export type RecoveryAction = { current_revision: FileRevision; path: string; target: FileTarget; type: "refresh_file" } | { conversation_id: string; type: "refresh_conversation" } | { run_id: string; type: "refresh_run" } | { after: string; type: "resume_events" };

export type RemoteEnvironment = { name: string; value?: string | null };

export type RemoteGitOperation = "status" | "diff";

export type RemoteToolAction = { columns: number; directory: string; input: string; rows: number; type: "terminal" } | { arguments: Array<string>; directory: string; environment: Array<RemoteEnvironment>; type: "process" } | { operation: RemoteGitOperation; type: "git" } | { directory: string; environment: Array<RemoteEnvironment>; script: string; type: "shell" } | { content: string; path: string; type: "write_file" } | { path: string; type: "read_file" };

export type RemoteToolOutcome = { result: RemoteToolResult; type: "completed" } | { error: WireError; type: "failed" };

export type RemoteToolResult = { operation_id: string; type: "approval_required" } | { exit_code?: number | null; stderr: string; stdout: string; type: "process" } | { type: "written" } | { content: string; type: "file" };

export type RestartMetadata = { current_snapshot_revision: string; minimum_available_cursor: string; reason: "cursor_expired" } | { current_snapshot_revision: string; reason: "cursor_ahead" } | { current_snapshot_revision: string; reason: "pagination_stale" };

export type RetentionPolicy = "retain" | "forget_after_final_run";

export type RevisionConflict = { current_revision: string; safe_state: ConflictState };

export type Run = { conversation_id: string; created_at_unix_ms: number; ended_at_unix_ms?: number | null; lifecycle: RunLifecycle; name?: Name | null; revision: string; run_id: string };

export type RunActivity = "working" | "waiting_for_user" | "waiting_for_approval" | "waiting_for_auth" | "waiting_for_quota" | "reconnecting";

export type RunLifecycle = "created" | "starting" | "active" | "stopping" | "completed" | "failed" | "canceled" | "lost";

export type TurnOutcome = "completed" | "interrupted";

export type UtilityInput = { opening_context: string; purpose: "naming"; title: string } | { instructions: string; patch: string; purpose: "git_text" } | { prompt: string; purpose: "autodelete" };

export type WireError = { category: ErrorCategory; code: string; message: string; recovery_actions?: Array<RecoveryAction>; restart?: RestartMetadata | null; retryable: boolean; revision_conflict?: RevisionConflict | null };

export type WorkingTree = { kind: "no_project" } | { kind: "workspace"; project_id: string } | { kind: "local_checkout"; project_id: string };
