// Generated by just craft-contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


public struct RawJSON { public let source: String }

public typealias PresentationBlock = RawJSON

public enum BrokerPermission: String {
    case `artifact_read` = "artifact_read"
    case `artifact_write` = "artifact_write"
    case `remote_tools` = "remote_tools"
}

public enum CraftAction {
    case `invoke`(CraftActionInvoke)
    case `approval`(CraftActionApproval)
}

public enum CraftApprovalDecision: String {
    case `allow_once` = "allow_once"
    case `deny` = "deny"
}

public enum CraftCommand {
    case `recover`(CraftCommandRecover)
    case `start`(CraftCommandStart)
    case `acknowledge`(CraftCommandAcknowledge)
    case `turn`(CraftCommandTurn)
    case `action`(CraftCommandAction)
    case `shutdown`(CraftCommandShutdown)
}

public enum CraftEvent {
    case `turn_started`(CraftEventTurnStarted)
    case `turn_ended`(CraftEventTurnEnded)
    case `file_changed`(CraftEventFileChanged)
    case `run_launch_failed`(CraftEventRunLaunchFailed)
    case `run_started`(CraftEventRunStarted)
    case `activity`(CraftEventActivity)
    case `progress`(CraftEventProgress)
    case `run_recovered`(CraftEventRunRecovered)
    case `run_ended`(CraftEventRunEnded)
    case `output`(CraftEventOutput)
    case `completed`(CraftEventCompleted)
}

public struct CraftFeature {
    public let `name`: String
    public let `required`: Bool?
}

public struct CraftFileChange {
    public let `activity_id`: String
    public let `after_mode`: String
    public let `after_object`: String
    public let `before_mode`: String
    public let `before_object`: String
    public let `path`: String
}

public struct CraftFork {
    public let `checkpoint_commit`: String
    public let `checkpoint_tree`: String
    public let `checkpoint_turn`: UInt32
    public let `source_conversation_id`: String
    public let `source_native_conversation`: String
    public let `source_run_id`: String
}

public struct CraftHello {
    public let `execution_id`: String
    public let `fork`: CraftFork?
    public let `protocol`: ProtocolOffer
    public let `resume`: CraftResume?
    public let `specification`: ProtocolOffer
}

public enum CraftHostAccess {
    case `executable`(CraftHostAccessExecutable)
    case `filesystem`(CraftHostAccessFilesystem)
    case `environment`(CraftHostAccessEnvironment)
    case `network`(CraftHostAccessNetwork)
}

public struct CraftReady {
    public let `enabled_features`: [String]
    public let `protocol`: NegotiatedProtocol
    public let `specification`: CraftSpecification
    public let `specification_protocol`: NegotiatedProtocol
}

public struct CraftResume {
    public let `native_conversation`: String
    public let `version`: ProtocolVersion
}

public struct CraftSpecification {
    public let `broker_permissions`: [BrokerPermission]?
    public let `features`: [CraftFeature]?
    public let `harness`: String
    public let `host_access`: [CraftHostAccess]?
    public let `id`: String
    public let `protocol`: ProtocolOffer
    public let `schema`: ProtocolVersion
}

public struct NegotiatedProtocol {
    public let `capabilities`: [String]
    public let `family`: ProtocolFamily
    public let `version`: ProtocolVersion
}

public enum Presentation {
    case `text`(PresentationText)
    case `markdown`(PresentationMarkdown)
    case `actions`(PresentationActions)
}

public struct PresentationAction {
    public let `id`: String
    public let `label`: String
}

public enum ProtocolFamily: String {
    case `client` = "client"
    case `craft` = "craft"
    case `helper` = "helper"
    case `specification` = "specification"
}

public struct ProtocolOffer {
    public let `capabilities`: [String]?
    public let `family`: ProtocolFamily
    public let `versions`: [ProtocolVersion]
}

public struct ProtocolVersion {
    public let `major`: UInt32
    public let `minor`: UInt32
}

public enum RunActivity: String {
    case `working` = "working"
    case `waiting_for_user` = "waiting_for_user"
    case `waiting_for_approval` = "waiting_for_approval"
    case `waiting_for_auth` = "waiting_for_auth"
    case `waiting_for_quota` = "waiting_for_quota"
    case `reconnecting` = "reconnecting"
}

public enum TurnOutcome: String {
    case `completed` = "completed"
    case `interrupted` = "interrupted"
}

public struct CraftActionInvoke {
    public let `action_id`: String
    public let `input`: Any
}

public struct CraftActionApproval {
    public let `decision`: CraftApprovalDecision
    public let `request_id`: String
}

public struct CraftCommandRecover {
    public let `checkpoint`: String
    public let `helper_socket`: String
    public let `id`: String
    public let `source_offset`: UInt64
}

public struct CraftCommandStart {
    public let `helper_socket`: String
    public let `id`: String
    public let `text`: String
}

public struct CraftCommandAcknowledge {
    public let `source_offset`: UInt64
}

public struct CraftCommandTurn {
    public let `id`: String
    public let `text`: String
}

public struct CraftCommandAction {
    public let `action`: CraftAction
    public let `id`: String
}

public struct CraftCommandShutdown {

}

public struct CraftEventTurnStarted {

}

public struct CraftEventTurnEnded {
    public let `outcome`: TurnOutcome
}

public struct CraftEventFileChanged {
    public let `change`: CraftFileChange
}

public struct CraftEventRunLaunchFailed {

}

public struct CraftEventRunStarted {
    public let `harness_pid`: UInt32
    public let `helper_pid`: UInt32
}

public struct CraftEventActivity {
    public let `activity`: RunActivity
}

public struct CraftEventProgress {
    public let `checkpoint`: String?
    public let `source_offset`: UInt64
}

public struct CraftEventRunRecovered {
    public let `helper_pid`: UInt32
    public let `source_offset`: UInt64
}

public struct CraftEventRunEnded {
    public let `exit_code`: Int32?
}

public struct CraftEventOutput {
    public let `native_event`: RawJSON
    public let `presentation`: [PresentationBlock]?
}

public struct CraftEventCompleted {
    public let `id`: String
    public let `native_conversation`: String
}

public struct CraftHostAccessExecutable {
    public let `name`: String
}

public struct CraftHostAccessFilesystem {
    public let `path`: String
}

public struct CraftHostAccessEnvironment {
    public let `name`: String
}

public struct CraftHostAccessNetwork {
    public let `destination`: String
}

public struct PresentationText {
    public let `text`: String
}

public struct PresentationMarkdown {
    public let `text`: String
}

public struct PresentationActions {
    public let `actions`: [PresentationAction]
}
