// Generated by just contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


public struct RawJSON { public let source: String }

public typealias PresentationBlock = RawJSON

public enum BrokerPermission: String {
    case `artifact_read` = "artifact_read"
    case `artifact_write` = "artifact_write"
    case `remote_tools` = "remote_tools"
}

public enum ConflictState {
    case `conversation`(ConflictStateConversation)
    case `run`(ConflictStateRun)
}

public struct Conversation {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public enum ConversationOrigin {
    case `new`(ConversationOriginNew)
    case `imported`(ConversationOriginImported)
    case `forked`(ConversationOriginForked)
}

public enum CraftAction {
    case `invoke`(CraftActionInvoke)
    case `approval`(CraftActionApproval)
}

public enum CraftApprovalDecision: String {
    case `allow_once` = "allow_once"
    case `deny` = "deny"
}

public struct CraftApprovalRequest {
    public let `action`: String
    public let `request_id`: String
    public let `tool`: String
}

public enum CraftCommand {
    case `constrain_subagents`(CraftCommandConstrainSubagents)
    case `configure_remote_tools`(CraftCommandConfigureRemoteTools)
    case `remote_tool_result`(CraftCommandRemoteToolResult)
    case `recover`(CraftCommandRecover)
    case `start`(CraftCommandStart)
    case `acknowledge`(CraftCommandAcknowledge)
    case `turn`(CraftCommandTurn)
    case `interrupt`(CraftCommandInterrupt)
    case `action`(CraftCommandAction)
    case `shutdown`(CraftCommandShutdown)
}

public enum CraftEvent {
    case `remote_tool`(CraftEventRemoteTool)
    case `usage`(CraftEventUsage)
    case `approval_requested`(CraftEventApprovalRequested)
    case `turn_started`(CraftEventTurnStarted)
    case `turn_ended`(CraftEventTurnEnded)
    case `file_changed`(CraftEventFileChanged)
    case `conversation_title`(CraftEventConversationTitle)
    case `run_title`(CraftEventRunTitle)
    case `process_title`(CraftEventProcessTitle)
    case `run_launch_failed`(CraftEventRunLaunchFailed)
    case `run_started`(CraftEventRunStarted)
    case `activity`(CraftEventActivity)
    case `progress`(CraftEventProgress)
    case `run_recovered`(CraftEventRunRecovered)
    case `run_ended`(CraftEventRunEnded)
    case `output`(CraftEventOutput)
    case `completed`(CraftEventCompleted)
}

public enum CraftExtensionReply {
    case `catalog`(CraftExtensionReplyCatalog)
    case `applied`(CraftExtensionReplyApplied)
    case `refused`(CraftExtensionReplyRefused)
}

public enum CraftExtensionRequest {
    case `catalog`(CraftExtensionRequestCatalog)
    case `inspect`(CraftExtensionRequestInspect)
    case `apply`(CraftExtensionRequestApply)
}

public struct CraftFeature {
    public let `name`: String
    public let `required`: Bool?
}

public struct CraftFileChange {
    public let `activity_id`: String
    public let `after_mode`: String
    public let `after_object`: String
    public let `before_mode`: String
    public let `before_object`: String
    public let `path`: String
}

public struct CraftFork {
    public let `checkpoint_commit`: String
    public let `checkpoint_tree`: String
    public let `checkpoint_turn`: UInt32
    public let `source_conversation_id`: String
    public let `source_native_conversation`: String
    public let `source_run_id`: String
}

public struct CraftHello {
    public let `execution_id`: String
    public let `fork`: CraftFork?
    public let `protocol`: ProtocolOffer
    public let `resume`: CraftResume?
    public let `specification`: ProtocolOffer
}

public enum CraftHostAccess {
    case `executable`(CraftHostAccessExecutable)
    case `filesystem`(CraftHostAccessFilesystem)
    case `environment`(CraftHostAccessEnvironment)
    case `network`(CraftHostAccessNetwork)
}

public struct CraftObservedUsage {
    public let `estimation`: CraftUsageEstimation
    public let `finality`: CraftUsageFinality
    public let `measurement`: CraftUsageMeasurement
    public let `model`: String?
    public let `tokens`: CraftUsageTokens
}

public enum CraftQuotaScope {
    case `provider_account`(CraftQuotaScopeProviderAccount)
    case `model`(CraftQuotaScopeModel)
}

public enum CraftQuotaUnit: String {
    case `tokens` = "tokens"
    case `requests` = "requests"
    case `credits` = "credits"
    case `share` = "share"
}

public struct CraftQuotaWindow {
    public let `estimation`: CraftUsageEstimation
    public let `finality`: CraftUsageFinality
    public let `limit`: UInt64?
    public let `resets_in_seconds`: UInt64?
    public let `scope`: CraftQuotaScope
    public let `unit`: CraftQuotaUnit
    public let `used`: UInt64
    public let `window`: String
    public let `window_seconds`: UInt64?
}

public struct CraftReady {
    public let `enabled_features`: [String]
    public let `protocol`: NegotiatedProtocol
    public let `specification`: CraftSpecification
    public let `specification_protocol`: NegotiatedProtocol
}

public struct CraftRemoteTool {
    public let `action`: RemoteToolAction
    public let `destination_plane_id`: String
    public let `operation_id`: String
    public let `workspace_id`: String
}

public struct CraftResume {
    public let `native_conversation`: String
    public let `version`: ProtocolVersion
}

public struct CraftReviewInput {
    public let `action`: String
    public let `tool`: String
    public let `transcript`: String
}

public struct CraftReviewModel {
    public let `model`: String
    public let `reviewer`: CraftReviewer
    public let `version`: UInt32
}

public struct CraftReviewReply {
    public let `model`: String
    public let `output`: String
    public let `reviewer`: CraftReviewer
    public let `version`: UInt32
}

public struct CraftReviewRequest {
    public let `binding_id`: String
    public let `credential_reference`: CredentialReference
    public let `input`: CraftReviewInput
    public let `model`: String
    public let `version`: UInt32
}

public enum CraftReviewer: String {
    case `native` = "native"
    case `equivalent` = "equivalent"
}

public struct CraftSpecification {
    public let `broker_permissions`: [BrokerPermission]?
    public let `features`: [CraftFeature]?
    public let `harness`: String
    public let `host_access`: [CraftHostAccess]?
    public let `id`: String
    public let `protocol`: ProtocolOffer
    public let `schema`: ProtocolVersion
}

public enum CraftUsage {
    case `observed`(CraftUsageObserved)
    case `quota`(CraftUsageQuota)
    case `unreachable`(CraftUsageUnreachable)
}

public enum CraftUsageEstimation: String {
    case `measured` = "measured"
    case `estimated` = "estimated"
}

public enum CraftUsageFinality: String {
    case `interim` = "interim"
    case `final` = "final"
}

public enum CraftUsageMeasurement {
    case `turn`(CraftUsageMeasurementTurn)
    case `run`(CraftUsageMeasurementRun)
}

public struct CraftUsageTokens {
    public let `cached_input`: UInt64?
    public let `input`: UInt64?
    public let `output`: UInt64?
    public let `reasoning`: UInt64?
}

public struct CraftUtilityModel {
    public let `model`: String
    public let `version`: UInt32
}

public struct CraftUtilityReply {
    public let `model`: String
    public let `output`: String
    public let `version`: UInt32
}

public struct CraftUtilityRequest {
    public let `binding_id`: String
    public let `credential_reference`: CredentialReference
    public let `input`: UtilityInput
    public let `model`: String
    public let `version`: UInt32
}

public struct CredentialItem {
    public let `account`: String
    public let `service`: String
}

public enum CredentialReference {
    case `platform_store`(CredentialReferencePlatformStore)
    case `external_helper`(CredentialReferenceExternalHelper)
    case `harness_native`(CredentialReferenceHarnessNative)
    case `session_only`(CredentialReferenceSessionOnly)
}

public enum ErrorCategory: String {
    case `invalid_input` = "invalid_input"
    case `unauthorized` = "unauthorized"
    case `conflict` = "conflict"
    case `unavailable` = "unavailable"
    case `incompatible` = "incompatible"
    case `rate_limited` = "rate_limited"
    case `not_found` = "not_found"
    case `outcome_unknown` = "outcome_unknown"
    case `internal` = "internal"
}

public enum ExtensionAction: String {
    case `install` = "install"
    case `update` = "update"
    case `disable` = "disable"
    case `remove` = "remove"
}

public struct ExtensionCatalog {
    public let `craft_id`: String
    public let `harness`: String
    public let `native_metadata`: String
}

public struct ExtensionConfirmation {
    public let `action`: ExtensionAction
    public let `catalog`: ExtensionCatalog
    public let `extension_id`: String
    public let `scope`: ExtensionScope
    public let `trust`: ExtensionTrust
}

public enum ExtensionScope: String {
    case `user` = "user"
}

public enum ExtensionTrust: String {
    case `same_user_executable` = "same_user_executable"
}

public struct FileRevision {
    public let `mode`: String
    public let `object`: String
}

public enum FileTarget {
    case `project`(FileTargetProject)
    case `workspace`(FileTargetWorkspace)
}

public struct Name {
    public let `source`: NameSource
    public let `value`: String
}

public enum NameSource: String {
    case `manual` = "manual"
    case `utility` = "utility"
    case `harness_native` = "harness_native"
    case `deterministic` = "deterministic"
}

public struct NegotiatedProtocol {
    public let `capabilities`: [String]
    public let `family`: ProtocolFamily
    public let `version`: ProtocolVersion
}

public struct NoVisaDestination {
    public let `plane_id`: String
    public let `ssh_endpoint`: String
    public let `workspace_id`: String
}

public struct NoVisaSelection {
    public let `account_binding_id`: String
    public let `conversation_id`: String
    public let `destinations`: [NoVisaDestination]
    public let `jet_equivalent`: [String]
    public let `native_unavailable`: [String]
    public let `origin_plane_id`: String
}

public enum Presentation {
    case `text`(PresentationText)
    case `markdown`(PresentationMarkdown)
    case `actions`(PresentationActions)
}

public struct PresentationAction {
    public let `id`: String
    public let `label`: String
}

public enum ProtocolFamily: String {
    case `client` = "client"
    case `craft` = "craft"
    case `helper` = "helper"
    case `specification` = "specification"
}

public struct ProtocolOffer {
    public let `capabilities`: [String]?
    public let `family`: ProtocolFamily
    public let `versions`: [ProtocolVersion]
}

public struct ProtocolVersion {
    public let `major`: UInt32
    public let `minor`: UInt32
}

public enum RecoveryAction {
    case `refresh_file`(RecoveryActionRefreshFile)
    case `refresh_conversation`(RecoveryActionRefreshConversation)
    case `refresh_run`(RecoveryActionRefreshRun)
    case `resume_events`(RecoveryActionResumeEvents)
}

public struct RemoteEnvironment {
    public let `name`: String
    public let `value`: String?
}

public enum RemoteGitOperation: String {
    case `status` = "status"
    case `diff` = "diff"
}

public enum RemoteToolAction {
    case `terminal`(RemoteToolActionTerminal)
    case `process`(RemoteToolActionProcess)
    case `git`(RemoteToolActionGit)
    case `shell`(RemoteToolActionShell)
    case `write_file`(RemoteToolActionWriteFile)
    case `read_file`(RemoteToolActionReadFile)
}

public enum RemoteToolOutcome {
    case `completed`(RemoteToolOutcomeCompleted)
    case `failed`(RemoteToolOutcomeFailed)
}

public enum RemoteToolResult {
    case `approval_required`(RemoteToolResultApprovalRequired)
    case `process`(RemoteToolResultProcess)
    case `written`(RemoteToolResultWritten)
    case `file`(RemoteToolResultFile)
}

public enum RestartMetadata {
    case `cursor_expired`(RestartMetadataCursorExpired)
    case `cursor_ahead`(RestartMetadataCursorAhead)
    case `pagination_stale`(RestartMetadataPaginationStale)
}

public enum RetentionPolicy: String {
    case `retain` = "retain"
    case `forget_after_final_run` = "forget_after_final_run"
}

public struct RevisionConflict {
    public let `current_revision`: String
    public let `safe_state`: ConflictState
}

public struct Run {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public enum RunActivity: String {
    case `working` = "working"
    case `waiting_for_user` = "waiting_for_user"
    case `waiting_for_approval` = "waiting_for_approval"
    case `waiting_for_auth` = "waiting_for_auth"
    case `waiting_for_quota` = "waiting_for_quota"
    case `reconnecting` = "reconnecting"
}

public enum RunLifecycle: String {
    case `created` = "created"
    case `starting` = "starting"
    case `active` = "active"
    case `stopping` = "stopping"
    case `completed` = "completed"
    case `failed` = "failed"
    case `canceled` = "canceled"
    case `lost` = "lost"
}

public enum TurnOutcome: String {
    case `completed` = "completed"
    case `interrupted` = "interrupted"
}

public enum UtilityInput {
    case `naming`(UtilityInputNaming)
    case `git_text`(UtilityInputGitText)
    case `autodelete`(UtilityInputAutodelete)
}

public struct WireError {
    public let `category`: ErrorCategory
    public let `code`: String
    public let `message`: String
    public let `recovery_actions`: [RecoveryAction]?
    public let `restart`: RestartMetadata?
    public let `retryable`: Bool
    public let `revision_conflict`: RevisionConflict?
}

public enum WorkingTree {
    case `no_project`(WorkingTreeNoProject)
    case `workspace`(WorkingTreeWorkspace)
    case `local_checkout`(WorkingTreeLocalCheckout)
}

public struct ConflictStateConversation {
    public let `conversation`: Conversation
}

public struct ConflictStateRun {
    public let `run`: Run
}

public struct ConversationOriginNew {

}

public struct ConversationOriginImported {
    public let `import_id`: String
}

public struct ConversationOriginForked {
    public let `checkpoint_turn`: UInt32
    public let `source_conversation_id`: String
    public let `source_run_id`: String
}

public struct CraftActionInvoke {
    public let `action_id`: String
    public let `input`: RawJSON
}

public struct CraftActionApproval {
    public let `decision`: CraftApprovalDecision
    public let `request_id`: String
}

public struct CraftCommandConstrainSubagents {
    public let `max_children`: UInt32?
}

public struct CraftCommandConfigureRemoteTools {
    public let `selection`: NoVisaSelection
}

public struct CraftCommandRemoteToolResult {
    public let `operation_id`: String
    public let `outcome`: RemoteToolOutcome
}

public struct CraftCommandRecover {
    public let `checkpoint`: String
    public let `helper_socket`: String
    public let `id`: String
    public let `source_offset`: UInt64
}

public struct CraftCommandStart {
    public let `helper_socket`: String
    public let `id`: String
    public let `text`: String
}

public struct CraftCommandAcknowledge {
    public let `source_offset`: UInt64
}

public struct CraftCommandTurn {
    public let `id`: String
    public let `text`: String
}

public struct CraftCommandInterrupt {
    public let `id`: String
}

public struct CraftCommandAction {
    public let `action`: CraftAction
    public let `id`: String
}

public struct CraftCommandShutdown {

}

public struct CraftEventRemoteTool {
    public let `call`: CraftRemoteTool
}

public struct CraftEventUsage {
    public let `usage`: CraftUsage
}

public struct CraftEventApprovalRequested {
    public let `request`: CraftApprovalRequest
}

public struct CraftEventTurnStarted {

}

public struct CraftEventTurnEnded {
    public let `outcome`: TurnOutcome
}

public struct CraftEventFileChanged {
    public let `change`: CraftFileChange
}

public struct CraftEventConversationTitle {
    public let `title`: String
}

public struct CraftEventRunTitle {
    public let `title`: String
}

public struct CraftEventProcessTitle {
    public let `pid`: UInt32
    public let `title`: String
}

public struct CraftEventRunLaunchFailed {

}

public struct CraftEventRunStarted {
    public let `harness_pid`: UInt32
    public let `helper_pid`: UInt32
}

public struct CraftEventActivity {
    public let `activity`: RunActivity
}

public struct CraftEventProgress {
    public let `checkpoint`: String?
    public let `source_offset`: UInt64
}

public struct CraftEventRunRecovered {
    public let `helper_pid`: UInt32
    public let `source_offset`: UInt64
}

public struct CraftEventRunEnded {
    public let `exit_code`: Int32?
}

public struct CraftEventOutput {
    public let `native_event`: RawJSON
    public let `presentation`: [PresentationBlock]?
}

public struct CraftEventCompleted {
    public let `id`: String
    public let `native_conversation`: String
}

public struct CraftExtensionReplyCatalog {
    public let `catalog`: ExtensionCatalog
}

public struct CraftExtensionReplyApplied {

}

public struct CraftExtensionReplyRefused {

}

public struct CraftExtensionRequestCatalog {

}

public struct CraftExtensionRequestInspect {
    public let `extension_id`: String
}

public struct CraftExtensionRequestApply {
    public let `confirmation`: ExtensionConfirmation
}

public struct CraftHostAccessExecutable {
    public let `name`: String
}

public struct CraftHostAccessFilesystem {
    public let `path`: String
}

public struct CraftHostAccessEnvironment {
    public let `name`: String
}

public struct CraftHostAccessNetwork {
    public let `destination`: String
}

public struct CraftQuotaScopeProviderAccount {

}

public struct CraftQuotaScopeModel {
    public let `model`: String
}

public struct CraftUsageObserved {
    public let `observed`: CraftObservedUsage
}

public struct CraftUsageQuota {
    public let `quota`: CraftQuotaWindow
}

public struct CraftUsageUnreachable {
    public let `reason`: String
}

public struct CraftUsageMeasurementTurn {
    public let `native_usage_id`: String?
    public let `turn`: String
}

public struct CraftUsageMeasurementRun {
    public let `native_usage_id`: String?
}

public struct CredentialReferencePlatformStore {
    public let `item`: CredentialItem
}

public struct CredentialReferenceExternalHelper {
    public let `helper`: String
}

public struct CredentialReferenceHarnessNative {

}

public struct CredentialReferenceSessionOnly {
    public let `established_at_daemon_start`: UInt64
}

public struct FileTargetProject {
    public let `project_id`: String
}

public struct FileTargetWorkspace {
    public let `workspace_id`: String
}

public struct PresentationText {
    public let `text`: String
}

public struct PresentationMarkdown {
    public let `text`: String
}

public struct PresentationActions {
    public let `actions`: [PresentationAction]
}

public struct RecoveryActionRefreshFile {
    public let `current_revision`: FileRevision
    public let `path`: String
    public let `target`: FileTarget
}

public struct RecoveryActionRefreshConversation {
    public let `conversation_id`: String
}

public struct RecoveryActionRefreshRun {
    public let `run_id`: String
}

public struct RecoveryActionResumeEvents {
    public let `after`: String
}

public struct RemoteToolActionTerminal {
    public let `columns`: Int64
    public let `directory`: String
    public let `input`: String
    public let `rows`: Int64
}

public struct RemoteToolActionProcess {
    public let `arguments`: [String]
    public let `directory`: String
    public let `environment`: [RemoteEnvironment]
}

public struct RemoteToolActionGit {
    public let `operation`: RemoteGitOperation
}

public struct RemoteToolActionShell {
    public let `directory`: String
    public let `environment`: [RemoteEnvironment]
    public let `script`: String
}

public struct RemoteToolActionWriteFile {
    public let `content`: String
    public let `path`: String
}

public struct RemoteToolActionReadFile {
    public let `path`: String
}

public struct RemoteToolOutcomeCompleted {
    public let `result`: RemoteToolResult
}

public struct RemoteToolOutcomeFailed {
    public let `error`: WireError
}

public struct RemoteToolResultApprovalRequired {
    public let `operation_id`: String
}

public struct RemoteToolResultProcess {
    public let `exit_code`: Int32?
    public let `stderr`: String
    public let `stdout`: String
}

public struct RemoteToolResultWritten {

}

public struct RemoteToolResultFile {
    public let `content`: String
}

public struct RestartMetadataCursorExpired {
    public let `current_snapshot_revision`: String
    public let `minimum_available_cursor`: String
}

public struct RestartMetadataCursorAhead {
    public let `current_snapshot_revision`: String
}

public struct RestartMetadataPaginationStale {
    public let `current_snapshot_revision`: String
}

public struct UtilityInputNaming {
    public let `opening_context`: String
    public let `title`: String
}

public struct UtilityInputGitText {
    public let `instructions`: String
    public let `patch`: String
}

public struct UtilityInputAutodelete {
    public let `prompt`: String
}

public struct WorkingTreeNoProject {

}

public struct WorkingTreeWorkspace {
    public let `project_id`: String
}

public struct WorkingTreeLocalCheckout {
    public let `project_id`: String
}
