// Generated by just craft-contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


export type RawJSON = string & { readonly __rawJSON: unique symbol };

export type PresentationBlock = RawJSON;

export type BrokerPermission = "artifact_read" | "artifact_write" | "remote_tools";

export type CraftAction = { action_id: string; input: unknown; kind: "invoke" } | { decision: CraftApprovalDecision; kind: "approval"; request_id: string };

export type CraftApprovalDecision = "allow_once" | "deny";

export type CraftCommand = { helper_socket: string; id: string; kind: "start"; text: string } | { kind: "acknowledge"; source_offset: number } | { id: string; kind: "turn"; text: string } | { action: CraftAction; id: string; kind: "action" } | { kind: "shutdown" };

export type CraftEvent = { kind: "run_launch_failed" } | { harness_pid: number; helper_pid: number; kind: "run_started" } | { activity: RunActivity; kind: "activity" } | { kind: "progress"; source_offset: number } | { exit_code?: number | null; kind: "run_ended" } | { kind: "output"; native_event: RawJSON; presentation?: Array<PresentationBlock> } | { id: string; kind: "completed"; native_conversation: string };

export type CraftFeature = { name: string; required?: boolean };

export type CraftHello = { execution_id: string; protocol: ProtocolOffer; resume?: CraftResume | null; specification: ProtocolOffer };

export type CraftHostAccess = { kind: "executable"; name: string } | { kind: "filesystem"; path: string } | { kind: "environment"; name: string } | { destination: string; kind: "network" };

export type CraftReady = { enabled_features: Array<string>; protocol: NegotiatedProtocol; specification: CraftSpecification; specification_protocol: NegotiatedProtocol };

export type CraftResume = { native_conversation: string; version: ProtocolVersion };

export type CraftSpecification = { broker_permissions?: Array<BrokerPermission>; features?: Array<CraftFeature>; harness: string; host_access?: Array<CraftHostAccess>; id: string; protocol: ProtocolOffer; schema: ProtocolVersion };

export type NegotiatedProtocol = { capabilities: Array<string>; family: ProtocolFamily; version: ProtocolVersion };

export type Presentation = { kind: "text"; text: string } | { kind: "markdown"; text: string } | { actions: Array<PresentationAction>; kind: "actions" };

export type PresentationAction = { id: string; label: string };

export type ProtocolFamily = "client" | "craft" | "helper" | "specification";

export type ProtocolOffer = { capabilities?: Array<string>; family: ProtocolFamily; versions: Array<ProtocolVersion> };

export type ProtocolVersion = { major: number; minor: number };

export type RunActivity = "working" | "waiting_for_user" | "waiting_for_approval" | "waiting_for_auth" | "waiting_for_quota" | "reconnecting";
