// Generated by just craft-contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


public struct RawJSON { public let source: String }

public typealias PresentationBlock = RawJSON

public enum BrokerPermission: String {
    case `artifact_read` = "artifact_read"
    case `artifact_write` = "artifact_write"
    case `remote_tools` = "remote_tools"
}

public enum CraftAction {
    case `invoke`(CraftActionInvoke)
    case `approval`(CraftActionApproval)
}

public enum CraftApprovalDecision: String {
    case `allow_once` = "allow_once"
    case `deny` = "deny"
}

public enum CraftCommand {
    case `turn`(CraftCommandTurn)
    case `action`(CraftCommandAction)
    case `shutdown`(CraftCommandShutdown)
}

public enum CraftEvent {
    case `output`(CraftEventOutput)
    case `completed`(CraftEventCompleted)
}

public struct CraftFeature {
    public let `name`: String
    public let `required`: Bool?
}

public struct CraftHello {
    public let `execution_id`: String
    public let `protocol`: ProtocolOffer
    public let `resume`: CraftResume?
    public let `specification`: ProtocolOffer
}

public enum CraftHostAccess {
    case `executable`(CraftHostAccessExecutable)
    case `filesystem`(CraftHostAccessFilesystem)
    case `environment`(CraftHostAccessEnvironment)
    case `network`(CraftHostAccessNetwork)
}

public struct CraftReady {
    public let `enabled_features`: [String]
    public let `protocol`: NegotiatedProtocol
    public let `specification`: CraftSpecification
    public let `specification_protocol`: NegotiatedProtocol
}

public struct CraftResume {
    public let `native_conversation`: String
    public let `version`: ProtocolVersion
}

public struct CraftSpecification {
    public let `broker_permissions`: [BrokerPermission]?
    public let `features`: [CraftFeature]?
    public let `harness`: String
    public let `host_access`: [CraftHostAccess]?
    public let `id`: String
    public let `protocol`: ProtocolOffer
    public let `schema`: ProtocolVersion
}

public struct NegotiatedProtocol {
    public let `capabilities`: [String]
    public let `family`: ProtocolFamily
    public let `version`: ProtocolVersion
}

public enum Presentation {
    case `text`(PresentationText)
    case `markdown`(PresentationMarkdown)
    case `actions`(PresentationActions)
}

public struct PresentationAction {
    public let `id`: String
    public let `label`: String
}

public enum ProtocolFamily: String {
    case `client` = "client"
    case `craft` = "craft"
    case `helper` = "helper"
    case `specification` = "specification"
}

public struct ProtocolOffer {
    public let `capabilities`: [String]?
    public let `family`: ProtocolFamily
    public let `versions`: [ProtocolVersion]
}

public struct ProtocolVersion {
    public let `major`: UInt32
    public let `minor`: UInt32
}

public struct CraftActionInvoke {
    public let `action_id`: String
    public let `input`: Any
}

public struct CraftActionApproval {
    public let `decision`: CraftApprovalDecision
    public let `request_id`: String
}

public struct CraftCommandTurn {
    public let `id`: String
    public let `text`: String
}

public struct CraftCommandAction {
    public let `action`: CraftAction
    public let `id`: String
}

public struct CraftCommandShutdown {

}

public struct CraftEventOutput {
    public let `native_event`: RawJSON
    public let `presentation`: [PresentationBlock]?
}

public struct CraftEventCompleted {
    public let `id`: String
    public let `native_conversation`: String
}

public struct CraftHostAccessExecutable {
    public let `name`: String
}

public struct CraftHostAccessFilesystem {
    public let `path`: String
}

public struct CraftHostAccessEnvironment {
    public let `name`: String
}

public struct CraftHostAccessNetwork {
    public let `destination`: String
}

public struct PresentationText {
    public let `text`: String
}

public struct PresentationMarkdown {
    public let `text`: String
}

public struct PresentationActions {
    public let `actions`: [PresentationAction]
}
