"""Generate GUI declarations from the emitted Craft schema; no codec guesses.

Native JSON and opaque Presentation blocks are represented as raw fragments.
Callers validate the original wire data with the schema before constructing
these models, and must not reconstruct raw fragments from parsed number trees.
"""
import json
from pathlib import Path

directory = Path(__file__).resolve().parents[1] / "packages/jet-protocol/contracts"
schema = json.loads((directory / "craft-v1.schema.json").read_text())
definitions = schema["$defs"]


def ts_type(item):
    if item is True or not item:
        return "unknown"
    if "$ref" in item:
        return item["$ref"].split("/")[-1]
    if "const" in item:
        return json.dumps(item["const"])
    if "enum" in item:
        return " | ".join(map(json.dumps, item["enum"]))
    if "anyOf" in item or "oneOf" in item:
        return " | ".join(ts_type(part) for part in item.get("anyOf", item.get("oneOf")))
    kind = item.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**item, "type": part}) for part in kind)
    if kind == "array":
        return f"Array<{ts_type(item['items'])}>"
    if kind == "object":
        fields = []
        for name, value in item.get("properties", {}).items():
            optional = "" if name in item.get("required", []) else "?"
            value_type = "RawJSON" if name == "native_event" else ts_type(value)
            fields.append(f"{name}{optional}: {value_type}")
        return "{ " + "; ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


swift_extra = {}


def swift_type(item, name):
    if item is True or not item:
        return "Any"
    if "$ref" in item:
        return item["$ref"].split("/")[-1]
    alternatives = item.get("anyOf", item.get("oneOf", []))
    if alternatives:
        nonnull = [part for part in alternatives if part.get("type") != "null"]
        if len(nonnull) == 1 and len(alternatives) == 2:
            return swift_type(nonnull[0], name) + "?"
        swift_extra[name] = item
        return name
    kind = item.get("type")
    if isinstance(kind, list):
        return swift_type({**item, "type": next(part for part in kind if part != "null")}, name) + "?"
    if kind == "array":
        return "[" + swift_type(item["items"], name + "Item") + "]"
    if "enum" in item or kind == "object":
        swift_extra[name] = item
        return name
    return {"string": "String", "integer": "UInt32", "number": "Double", "boolean": "Bool"}.get(kind, "Any")


def swift_declaration(name, item):
    choices = item.get("oneOf", item.get("anyOf", []))
    if choices and all(isinstance(part.get("const"), str) for part in choices):
        item = {"enum": [part["const"] for part in choices]}
    if "enum" in item:
        cases = [f'    case `{value}` = {json.dumps(value)}' for value in item["enum"]]
        return f"public enum {name}: String {{\n" + "\n".join(cases) + "\n}"
    alternatives = item.get("oneOf", item.get("anyOf"))
    if alternatives:
        cases = []
        for index, part in enumerate(alternatives):
            kind = part.get("properties", {}).get("kind", {}).get("const", f"variant{index}")
            child = name + "".join(word.title() for word in kind.split("_"))
            swift_extra[child] = part
            cases.append(f"    case `{kind}`({child})")
        return f"public enum {name} {{\n" + "\n".join(cases) + "\n}"
    if item.get("type") == "object":
        fields = []
        for field, value in item.get("properties", {}).items():
            if "const" in value:
                continue  # The enclosing tagged enum supplies the discriminator.
            kind = "RawJSON" if field == "native_event" else swift_type(value, name + field.title().replace("_", ""))
            if field not in item.get("required", []) and not kind.endswith("?"):
                kind += "?"
            fields.append(f"    public let `{field}`: {kind}")
        return f"public struct {name} {{\n" + "\n".join(fields) + "\n}"
    return f"public typealias {name} = {swift_type(item, name)}"


header = "// Generated by just craft-contracts. Do not edit.\n// Models only: validate against the schema and retain raw JSON before decoding.\n"
typescript = [header, "export type RawJSON = string & { readonly __rawJSON: unique symbol };", "export type PresentationBlock = RawJSON;"]
swift = [header, "public struct RawJSON { public let source: String }", "public typealias PresentationBlock = RawJSON"]
for name, item in sorted(definitions.items()):
    if name == "PresentationBlock":
        continue
    typescript.append(f"export type {name} = {ts_type(item)};")
    swift.append(swift_declaration(name, item))
while swift_extra:
    name = next(iter(swift_extra))
    swift.append(swift_declaration(name, swift_extra.pop(name)))
(directory / "CraftModels.ts").write_text("\n\n".join(typescript) + "\n")
(directory / "CraftModels.swift").write_text("\n\n".join(swift) + "\n")
