"""Generate GUI declarations from an emitted wire schema; no codec guesses.

Usage: wire-models.py <schema.json> <models.ts> <models.swift>

Native JSON and opaque Presentation blocks are represented as raw fragments.
Callers validate the original wire data with the schema before constructing
these models, and must not reconstruct raw fragments from parsed number trees.
"""
import json
import re
import sys
from pathlib import Path

schema_path, typescript_path, swift_path = map(Path, sys.argv[1:4])
definitions = json.loads(schema_path.read_text())["$defs"]


def is_raw(item):
    """An unconstrained schema: original JSON the caller must retain verbatim."""
    return item is True or not (set(item) - {"description"})


def ts_type(item):
    if is_raw(item):
        return "RawJSON"
    if "$ref" in item:
        return item["$ref"].split("/")[-1]
    if "const" in item:
        return json.dumps(item["const"])
    if "enum" in item:
        return " | ".join(map(json.dumps, item["enum"]))
    if "anyOf" in item or "oneOf" in item:
        return " | ".join(ts_type(part) for part in item.get("anyOf", item.get("oneOf")))
    kind = item.get("type")
    if isinstance(kind, list):
        return " | ".join(ts_type({**item, "type": part}) for part in kind)
    if kind == "array":
        return f"Array<{ts_type(item['items'])}>"
    if kind == "object":
        fields = []
        for name, value in item.get("properties", {}).items():
            optional = "" if name in item.get("required", []) else "?"
            fields.append(f"{name}{optional}: {ts_type(value)}")
        return "{ " + "; ".join(fields) + " }"
    return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(kind, "unknown")


swift_extra = {}


def swift_type(item, name):
    if is_raw(item):
        return "RawJSON"
    if "$ref" in item:
        return item["$ref"].split("/")[-1]
    alternatives = item.get("anyOf", item.get("oneOf", []))
    if alternatives:
        nonnull = [part for part in alternatives if part.get("type") != "null"]
        if len(nonnull) == 1 and len(alternatives) == 2:
            return swift_type(nonnull[0], name) + "?"
        swift_extra[name] = item
        return name
    kind = item.get("type")
    if isinstance(kind, list):
        return swift_type({**item, "type": next(part for part in kind if part != "null")}, name) + "?"
    if kind == "array":
        return "[" + swift_type(item["items"], name + "Item") + "]"
    if "enum" in item or kind == "object":
        swift_extra[name] = item
        return name
    if kind == "integer":
        return {"uint32": "UInt32", "uint64": "UInt64", "int32": "Int32", "int64": "Int64"}.get(item.get("format"), "Int64")
    return {"string": "String", "number": "Double", "boolean": "Bool"}.get(kind, "Any")


def discriminator(part):
    """The case name of a tagged branch: its one constant-valued property."""
    for value in part.get("properties", {}).values():
        if isinstance(value.get("const"), str):
            return value["const"]
    return None


def swift_declaration(name, item):
    choices = item.get("oneOf", item.get("anyOf", []))
    if choices and all(isinstance(part.get("const"), str) for part in choices):
        item = {"enum": [part["const"] for part in choices]}
    if "enum" in item:
        cases = [f'    case `{value}` = {json.dumps(value)}' for value in item["enum"]]
        return f"public enum {name}: String {{\n" + "\n".join(cases) + "\n}"
    alternatives = item.get("oneOf", item.get("anyOf"))
    if alternatives:
        cases = []
        for index, part in enumerate(alternatives):
            kind = discriminator(part) or f"variant{index}"
            child = name + "".join(word.title() for word in kind.split("_"))
            swift_extra[child] = part
            cases.append(f"    case `{kind}`({child})")
        return f"public enum {name} {{\n" + "\n".join(cases) + "\n}"
    if item.get("type") == "object":
        fields = []
        for field, value in item.get("properties", {}).items():
            if "const" in value:
                continue  # The enclosing tagged enum supplies the discriminator.
            kind = swift_type(value, name + field.title().replace("_", ""))
            if field not in item.get("required", []) and not kind.endswith("?"):
                kind += "?"
            fields.append(f"    public let `{field}`: {kind}")
        return f"public struct {name} {{\n" + "\n".join(fields) + "\n}"
    return f"public typealias {name} = {swift_type(item, name)}"


header = "// Generated by just contracts. Do not edit.\n// Models only: validate against the schema and retain raw JSON before decoding.\n"
typescript, swift = [], []
if "PresentationBlock" in definitions:
    typescript.append("export type PresentationBlock = RawJSON;")
    swift.append("public typealias PresentationBlock = RawJSON")
for name, item in sorted(definitions.items()):
    if name == "PresentationBlock":
        continue
    typescript.append(f"export type {name} = {ts_type(item)};")
    swift.append(swift_declaration(name, item))
while swift_extra:
    name = next(iter(swift_extra))
    swift.append(swift_declaration(name, swift_extra.pop(name)))
if any("RawJSON" in declaration for declaration in typescript + swift):
    typescript.insert(0, "export type RawJSON = string & { readonly __rawJSON: unique symbol };")
    swift.insert(0, "public struct RawJSON { public let source: String }")
typescript.insert(0, header)
swift.insert(0, header)


def swift_problems(source):
    """Swift does not build on every developer's platform, so check here what
    a compiler would reject: a type declared twice, a type never declared, or
    an enum that repeats a case."""
    declared = re.findall(r"^public (?:struct|enum|typealias) (\w+)", source, re.M)
    referenced = set(re.findall(r": \[?(\w+)\??\]?$", source, re.M))
    referenced |= set(re.findall(r"case `[^`]+`\((\w+)\)", source))
    builtin = {"String", "Int64", "UInt64", "Int32", "UInt32", "Double", "Bool", "Any"}
    problems = [f"declared twice: {name}" for name in sorted({name for name in declared if declared.count(name) > 1})]
    problems += [f"never declared: {name}" for name in sorted(referenced - set(declared) - builtin)]
    for name, body in re.findall(r"public enum (\w+) \{\n((?:    case [^\n]*\n)+)\}", source):
        cases = re.findall(r"case `([^`]+)`", body)
        if len(cases) != len(set(cases)):
            problems.append(f"repeats a case: {name}")
    return problems


swift_source = "\n\n".join(swift) + "\n"
problems = swift_problems(swift_source)
if problems:
    sys.exit(f"{swift_path}: " + "; ".join(problems))
typescript_path.write_text("\n\n".join(typescript) + "\n")
swift_path.write_text(swift_source)
