// Generated by just contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


public struct RawJSON { public let source: String }

public struct AccountBinding {
    public let `binding_id`: String
    public let `created_at_unix_ms`: Int64
    public let `credential_reference`: CredentialReference
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct AccountBindingList {
    public let `bindings`: [AccountBindingStatus]
    public let `cursor`: String
}

public struct AccountBindingStatus {
    public let `binding`: AccountBinding
    public let `credential_state`: CredentialState
}

public enum Actor {
    case `interactive_client`(ActorInteractiveClient)
}

public enum ArtifactAvailability: String {
    case `stored` = "stored"
    case `run_budget_exceeded` = "run_budget_exceeded"
    case `artifact_size_exceeded` = "artifact_size_exceeded"
}

public enum AuditBreach {
    case `head_missing`(AuditBreachHeadMissing)
    case `head_not_in_store`(AuditBreachHeadNotInStore)
    case `head_diverged`(AuditBreachHeadDiverged)
    case `record_altered`(AuditBreachRecordAltered)
    case `target_altered`(AuditBreachTargetAltered)
}

public struct AuditEntry {
    public let `actor`: Actor
    public let `decision`: String
    public let `epoch`: String
    public let `outcome`: AuditOutcome
    public let `plane_id`: String
    public let `record_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `risk`: AuditRisk
    public let `sequence`: String
    public let `target`: AuditTarget
}

public struct AuditHead {
    public let `entry_hash`: String
    public let `epoch`: String
    public let `sequence`: String
}

public enum AuditOutcome: String {
    case `succeeded` = "succeeded"
    case `denied` = "denied"
    case `failed` = "failed"
}

public enum AuditRisk: String {
    case `routine` = "routine"
    case `elevated` = "elevated"
    case `destructive` = "destructive"
}

public struct AuditTarget {
    public let `identity`: String?
    public let `kind`: String
    public let `reference`: String
}

public enum BaseSelection {
    case `head`(BaseSelectionHead)
    case `revision`(BaseSelectionRevision)
}

public enum CapabilityObservation {
    case `last_observed`(CapabilityObservationLastObserved)
    case `fresh`(CapabilityObservationFresh)
}

public struct CapabilitySnapshot {
    public let `core_version`: String
    public let `crafts`: [InstalledCraft]
    public let `credential_store`: CredentialStoreStatus
    public let `degraded`: [DegradedCondition]
    public let `external_tools`: [ExternalToolStatus]
    public let `harnesses`: [String]
    public let `observed_at_unix_ms`: Int64
    public let `platform`: Platform
}

public struct ChangeArtifact {
    public let `availability`: ArtifactAvailability?
    public let `sha256`: String
    public let `size`: UInt64
}

public struct ChangeArtifactChunk {
    public let `artifact`: ChangeArtifact
    public let `bytes`: [Int64]
    public let `offset`: String
}

public struct ChangeDiff {
    public let `after`: ChangeSnapshot
    public let `artifact`: ChangeArtifact
    public let `before`: ChangeSnapshot
    public let `cursor`: String
    public let `files`: [ChangedFile]
    public let `latest_turn`: UInt32
    public let `next_page`: PageCursor?
    public let `outcome`: TurnOutcome?
    public let `patch`: String
    public let `patch_truncated`: Bool
    public let `plane_id`: String
    public let `run_id`: String
    public let `scope`: DiffScope
    public let `total_files`: UInt32
    public let `workspace_id`: String?
}

public enum ChangeKind: String {
    case `added` = "added"
    case `modified` = "modified"
    case `deleted` = "deleted"
}

public enum ChangeOrigin {
    case `user_edit`(ChangeOriginUserEdit)
    case `workspace_terminal`(ChangeOriginWorkspaceTerminal)
    case `harness`(ChangeOriginHarness)
    case `mixed`(ChangeOriginMixed)
    case `external_or_unknown`(ChangeOriginExternalOrUnknown)
}

public struct ChangeSnapshot {
    public let `commit`: String
    public let `content_complete`: Bool
    public let `tree`: String
    public let `uncommitted`: ChangeArtifact
}

public struct ChangedFile {
    public let `after_mode`: String
    public let `after_object`: String?
    public let `after_size`: UInt64?
    public let `before_mode`: String
    public let `before_object`: String?
    public let `before_size`: UInt64?
    public let `origin`: ChangeOrigin
    public let `path`: String
}

public enum Checkout: String {
    case `full` = "full"
    case `sparse` = "sparse"
}

public struct ClientHello {
    public let `capabilities`: [String]?
    public let `client_id`: String
    public let `codec`: String
    public let `max_control_frame`: UInt32
    public let `max_data_frame`: UInt32
    public let `minor`: UInt32
    public let `protocol`: VersionRange
}

public enum ClientMessage {
    case `attach_terminal`(ClientMessageAttachTerminal)
    case `resize_terminal`(ClientMessageResizeTerminal)
    case `query`(ClientMessageQuery)
    case `command`(ClientMessageCommand)
}

public struct ClientPublicKey {
    public let `algorithm`: PairingKeyAlgorithm
    public let `key`: String
}

public enum CommandRequest {
    case `create_schedule`(CommandRequestCreateSchedule)
    case `cancel_schedule`(CommandRequestCancelSchedule)
    case `apply_user_edit`(CommandRequestApplyUserEdit)
    case `submit_review`(CommandRequestSubmitReview)
    case `set_conversation_name`(CommandRequestSetConversationName)
    case `set_run_name`(CommandRequestSetRunName)
    case `open_terminal`(CommandRequestOpenTerminal)
    case `close_terminal`(CommandRequestCloseTerminal)
    case `withdraw_turn`(CommandRequestWithdrawTurn)
    case `submit_turn`(CommandRequestSubmitTurn)
    case `resolve_execution`(CommandRequestResolveExecution)
    case `interrupt_turn`(CommandRequestInterruptTurn)
    case `stop_run`(CommandRequestStopRun)
    case `start_run`(CommandRequestStartRun)
    case `create_conversation`(CommandRequestCreateConversation)
    case `fork_conversation`(CommandRequestForkConversation)
    case `create_run`(CommandRequestCreateRun)
    case `set_setting`(CommandRequestSetSetting)
    case `clear_setting`(CommandRequestClearSetting)
    case `bind_account`(CommandRequestBindAccount)
    case `unbind_account`(CommandRequestUnbindAccount)
    case `begin_audit_epoch`(CommandRequestBeginAuditEpoch)
    case `set_pairing_gate`(CommandRequestSetPairingGate)
    case `open_pairing`(CommandRequestOpenPairing)
    case `claim_pairing`(CommandRequestClaimPairing)
    case `confirm_pairing`(CommandRequestConfirmPairing)
    case `complete_pairing`(CommandRequestCompletePairing)
    case `set_paired_client_access`(CommandRequestSetPairedClientAccess)
    case `revoke_paired_client`(CommandRequestRevokePairedClient)
    case `transition_run`(CommandRequestTransitionRun)
    case `register_project`(CommandRequestRegisterProject)
    case `promote_workspace`(CommandRequestPromoteWorkspace)
    case `import_conversation`(CommandRequestImportConversation)
    case `resume_imported_conversation`(CommandRequestResumeImportedConversation)
}

public enum CommandResponse {
    case `schedule_created`(CommandResponseScheduleCreated)
    case `schedule_canceled`(CommandResponseScheduleCanceled)
    case `user_edit_applied`(CommandResponseUserEditApplied)
    case `conversation_named`(CommandResponseConversationNamed)
    case `run_named`(CommandResponseRunNamed)
    case `terminal`(CommandResponseTerminal)
    case `turn_withdrawn`(CommandResponseTurnWithdrawn)
    case `turn_admitted`(CommandResponseTurnAdmitted)
    case `run_control_accepted`(CommandResponseRunControlAccepted)
    case `execution_resolution_recorded`(CommandResponseExecutionResolutionRecorded)
    case `conversation_created`(CommandResponseConversationCreated)
    case `run_created`(CommandResponseRunCreated)
    case `run_transitioned`(CommandResponseRunTransitioned)
    case `setting_set`(CommandResponseSettingSet)
    case `setting_cleared`(CommandResponseSettingCleared)
    case `account_bound`(CommandResponseAccountBound)
    case `account_unbound`(CommandResponseAccountUnbound)
    case `pairing_gate_set`(CommandResponsePairingGateSet)
    case `pairing_opened`(CommandResponsePairingOpened)
    case `pairing_claimed`(CommandResponsePairingClaimed)
    case `pairing_confirmed`(CommandResponsePairingConfirmed)
    case `pairing_completed`(CommandResponsePairingCompleted)
    case `paired_client_access_set`(CommandResponsePairedClientAccessSet)
    case `paired_client_revoked`(CommandResponsePairedClientRevoked)
    case `audit_epoch_begun`(CommandResponseAuditEpochBegun)
    case `project_registered`(CommandResponseProjectRegistered)
    case `workspace_promotion_recorded`(CommandResponseWorkspacePromotionRecorded)
    case `conversation_imported`(CommandResponseConversationImported)
}

public enum ConflictKind: String {
    case `diverged` = "diverged"
    case `untracked` = "untracked"
    case `staged` = "staged"
}

public enum ConflictState {
    case `conversation`(ConflictStateConversation)
    case `run`(ConflictStateRun)
}

public struct ConnectionProof {
    public let `signature`: String
}

public struct Conversation {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct ConversationList {
    public let `conversations`: [Conversation]
    public let `cursor`: String
    public let `next_page`: PageCursor?
}

public enum ConversationOrigin {
    case `new`(ConversationOriginNew)
    case `imported`(ConversationOriginImported)
    case `forked`(ConversationOriginForked)
}

public struct ConversationSnapshot {
    public let `conversation`: Conversation
    public let `cursor`: String
    public let `runs`: [Run]
    public let `workspace`: Workspace?
}

public struct CredentialItem {
    public let `account`: String
    public let `service`: String
}

public enum CredentialReference {
    case `platform_store`(CredentialReferencePlatformStore)
    case `external_helper`(CredentialReferenceExternalHelper)
    case `harness_native`(CredentialReferenceHarnessNative)
    case `session_only`(CredentialReferenceSessionOnly)
}

public enum CredentialSource {
    case `platform_store`(CredentialSourcePlatformStore)
    case `external_helper`(CredentialSourceExternalHelper)
    case `harness_native`(CredentialSourceHarnessNative)
    case `session_only`(CredentialSourceSessionOnly)
}

public enum CredentialState {
    case `resolvable`(CredentialStateResolvable)
    case `resolved_at_use`(CredentialStateResolvedAtUse)
    case `waiting_for_unlock`(CredentialStateWaitingForUnlock)
    case `unavailable`(CredentialStateUnavailable)
    case `invalidated_by_restart`(CredentialStateInvalidatedByRestart)
}

public enum CredentialStoreKind: String {
    case `apple_keychain` = "apple_keychain"
    case `secret_service` = "secret_service"
}

public enum CredentialStoreStatus {
    case `available`(CredentialStoreStatusAvailable)
    case `locked`(CredentialStoreStatusLocked)
    case `unavailable`(CredentialStoreStatusUnavailable)
}

public enum DegradedCondition {
    case `missing_external_tool`(DegradedConditionMissingExternalTool)
    case `no_harness_available`(DegradedConditionNoHarnessAvailable)
    case `credential_store_unavailable`(DegradedConditionCredentialStoreUnavailable)
    case `credential_store_locked`(DegradedConditionCredentialStoreLocked)
}

public enum DiffScope {
    case `current`(DiffScopeCurrent)
    case `final`(DiffScopeFinal)
    case `historical`(DiffScopeHistorical)
    case `turn`(DiffScopeTurn)
}

public struct EditableFile {
    public let `content`: String?
    public let `cursor`: String
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public enum EntryKind {
    case `file`(EntryKindFile)
    case `directory`(EntryKindDirectory)
    case `other`(EntryKindOther)
    case `missing`(EntryKindMissing)
}

public enum ErrorCategory: String {
    case `invalid_input` = "invalid_input"
    case `unauthorized` = "unauthorized"
    case `conflict` = "conflict"
    case `unavailable` = "unavailable"
    case `incompatible` = "incompatible"
    case `rate_limited` = "rate_limited"
    case `not_found` = "not_found"
    case `outcome_unknown` = "outcome_unknown"
    case `internal` = "internal"
}

public struct Event {
    public let `actor`: Actor
    public let `conversation_id`: String?
    public let `event_id`: String
    public let `kind`: String
    public let `origin`: EventOrigin?
    public let `payload`: RawJSON
    public let `payload_version`: UInt32
    public let `recorded_at_unix_ms`: Int64
    public let `run_id`: String?
    public let `sequence`: String
}

public enum EventOrigin {
    case `scheduled_task`(EventOriginScheduledTask)
    case `harness`(EventOriginHarness)
    case `run_supervisor`(EventOriginRunSupervisor)
}

public struct EventPage {
    public let `cursor`: String
    public let `events`: [Event]
}

public enum ExecutionAction: String {
    case `adopt` = "adopt"
    case `leave` = "leave"
    case `terminate` = "terminate"
}

public struct ExecutionMetadata {
    public let `helper_pid`: UInt32
    public let `instance`: String
    public let `project_root`: String
    public let `root`: String
    public let `version`: String
}

public enum ExecutionRole: String {
    case `run` = "run"
    case `terminal` = "terminal"
}

public struct ExternalConversation {
    public let `harness`: String
    public let `import_id`: String?
    public let `native_conversation`: String
    public let `origin`: ExternalOrigin
    public let `process`: ExternalProcess
}

public struct ExternalConversationList {
    public let `cursor`: String
    public let `discovered`: [ExternalConversation]
    public let `imported`: [ImportedConversation]
}

public enum ExternalOrigin {
    case `project`(ExternalOriginProject)
    case `unregistered`(ExternalOriginUnregistered)
    case `unknown`(ExternalOriginUnknown)
}

public enum ExternalProcess {
    case `none`(ExternalProcessNone)
    case `external`(ExternalProcessExternal)
    case `cooperating`(ExternalProcessCooperating)
}

public enum ExternalTool: String {
    case `git` = "git"
    case `git-lfs` = "git-lfs"
    case `ssh` = "ssh"
    case `tailscale` = "tailscale"
}

public struct ExternalToolStatus {
    public let `availability`: ToolAvailability
    public let `tool`: ExternalTool
}

public struct FileRevision {
    public let `mode`: String
    public let `object`: String
}

public enum FileTarget {
    case `project`(FileTargetProject)
    case `workspace`(FileTargetWorkspace)
}

public struct GitLink {
    public let `commit`: String
    public let `path`: String
}

public struct ImportedConversation {
    public let `harness`: String
    public let `import_id`: String
    public let `imported_at_unix_ms`: Int64
    public let `imported_by`: Actor
    public let `native_conversation`: String
    public let `resumed_as`: String?
    public let `working_directory`: String?
}

public struct InstalledCraft {
    public let `craft_id`: String
    public let `harnesses`: [String]
    public let `version`: String
}

public struct ManagedProcess {
    public let `label`: String?
    public let `pid`: UInt32
    public let `role`: ManagedProcessRole
    public let `running`: Bool
}

public enum ManagedProcessRole: String {
    case `helper` = "helper"
    case `harness` = "harness"
}

public struct Name {
    public let `source`: NameSource
    public let `value`: String
}

public enum NameSource: String {
    case `manual` = "manual"
    case `utility` = "utility"
    case `harness_native` = "harness_native"
    case `deterministic` = "deterministic"
}

public struct OrphanedExecution {
    public let `execution_id`: String
    public let `metadata`: ExecutionMetadata?
    public let `role`: ExecutionRole?
}

public struct OrphanedExecutions {
    public let `executions`: [OrphanedExecution]
    public let `next`: String?
}

public typealias PageCursor = String

public struct PairedClient {
    public let `access`: PairedClientAccess
    public let `client_id`: String
    public let `key`: ClientPublicKey
    public let `paired_at_unix_ms`: Int64
    public let `pairing_protocol`: String
}

public enum PairedClientAccess: String {
    case `enabled` = "enabled"
    case `disabled` = "disabled"
}

public enum PairingDisclosure {
    case `manual_code`(PairingDisclosureManualCode)
    case `qr_payload`(PairingDisclosureQrPayload)
    case `already_disclosed`(PairingDisclosureAlreadyDisclosed)
}

public enum PairingEnd: String {
    case `expired` = "expired"
    case `too_many_attempts` = "too_many_attempts"
    case `gate_closed` = "gate_closed"
}

public enum PairingGate: String {
    case `open` = "open"
    case `closed` = "closed"
}

public enum PairingKeyAlgorithm: String {
    case `ed25519` = "ed25519"
}

public enum PairingMethod {
    case `manual_code`(PairingMethodManualCode)
    case `qr_payload`(PairingMethodQrPayload)
}

public enum PairingProgress {
    case `offered`(PairingProgressOffered)
    case `awaiting_confirmation`(PairingProgressAwaitingConfirmation)
    case `confirmed`(PairingProgressConfirmed)
    case `ended`(PairingProgressEnded)
}

public struct PairingSnapshot {
    public let `clients`: [PairedClient]?
    public let `cursor`: String
    public let `gate`: PairingGate
    public let `pending`: PendingPairing?
}

public struct PendingPairing {
    public let `attempts_remaining`: UInt32
    public let `expires_at_unix_ms`: Int64
    public let `method`: PairingMethod
    public let `offer_id`: String
    public let `opened_at_unix_ms`: Int64
    public let `progress`: PairingProgress
}

public struct PlaneStatus {
    public let `core_version`: String
    public let `cursor`: String?
    public let `daemon_starts`: UInt64
    public let `plane_id`: String
    public let `security`: SecurityState?
    public let `started_at_unix_ms`: Int64
}

public struct Platform {
    public let `architecture`: String
    public let `operating_system`: String
}

public struct Project {
    public let `project_id`: String
    public let `registered_at_unix_ms`: Int64
    public let `registered_by`: Actor
    public let `root`: String
}

public struct ProjectEntry {
    public let `cursor`: String
    public let `kind`: EntryKind
    public let `path`: String
    public let `project_id`: String
}

public struct ProjectList {
    public let `cursor`: String
    public let `projects`: [Project]
}

public struct ProjectPreview {
    public let `registrability`: Registrability
    public let `root`: String
}

public struct PromotedChange {
    public let `kind`: ChangeKind
    public let `path`: String
}

public struct PromotionBinding {
    public let `actor`: String
    public let `base_commit`: String
    public let `conflicts`: [PromotionConflict]
    public let `destination`: PromotionDestination
    public let `destination_commit`: String
    public let `destination_dirty`: Bool
    public let `destination_tree`: String
    public let `result_tree`: String
    public let `workspace_id`: String
    public let `workspace_tree`: String
}

public struct PromotionConflict {
    public let `kind`: ConflictKind
    public let `path`: String
}

public enum PromotionDestination {
    case `local_checkout`(PromotionDestinationLocalCheckout)
    case `branch`(PromotionDestinationBranch)
}

public struct PromotionPreview {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `changes`: [PromotedChange]
    public let `cursor`: String
}

public enum PromotionState: String {
    case `applying` = "applying"
    case `promoted` = "promoted"
    case `conflicted` = "conflicted"
    case `failed` = "failed"
    case `outcome_unknown` = "outcome_unknown"
}

public enum QueryRequest {
    case `scheduled_tasks`(QueryRequestScheduledTasks)
    case `editable_file`(QueryRequestEditableFile)
    case `workspace_terminals`(QueryRequestWorkspaceTerminals)
    case `change_artifact`(QueryRequestChangeArtifact)
    case `change_diff`(QueryRequestChangeDiff)
    case `next_change_diff`(QueryRequestNextChangeDiff)
    case `turn_queue`(QueryRequestTurnQueue)
    case `orphaned_executions`(QueryRequestOrphanedExecutions)
    case `run_execution`(QueryRequestRunExecution)
    case `status`(QueryRequestStatus)
    case `conversations`(QueryRequestConversations)
    case `next_conversations`(QueryRequestNextConversations)
    case `conversation`(QueryRequestConversation)
    case `capabilities`(QueryRequestCapabilities)
    case `account_bindings`(QueryRequestAccountBindings)
    case `settings`(QueryRequestSettings)
    case `events`(QueryRequestEvents)
    case `pairing`(QueryRequestPairing)
    case `security_audit`(QueryRequestSecurityAudit)
    case `projects`(QueryRequestProjects)
    case `preview_project`(QueryRequestPreviewProject)
    case `project_entry`(QueryRequestProjectEntry)
    case `preview_promotion`(QueryRequestPreviewPromotion)
    case `search`(QueryRequestSearch)
    case `external_conversations`(QueryRequestExternalConversations)
}

public enum QueryResponse {
    case `scheduled_tasks`(QueryResponseScheduledTasks)
    case `editable_file`(QueryResponseEditableFile)
    case `workspace_terminals`(QueryResponseWorkspaceTerminals)
    case `change_artifact`(QueryResponseChangeArtifact)
    case `change_diff`(QueryResponseChangeDiff)
    case `turn_queue`(QueryResponseTurnQueue)
    case `orphaned_executions`(QueryResponseOrphanedExecutions)
    case `run_execution`(QueryResponseRunExecution)
    case `status`(QueryResponseStatus)
    case `conversations`(QueryResponseConversations)
    case `conversation`(QueryResponseConversation)
    case `capabilities`(QueryResponseCapabilities)
    case `account_bindings`(QueryResponseAccountBindings)
    case `settings`(QueryResponseSettings)
    case `events`(QueryResponseEvents)
    case `pairing`(QueryResponsePairing)
    case `security_audit`(QueryResponseSecurityAudit)
    case `projects`(QueryResponseProjects)
    case `project_preview`(QueryResponseProjectPreview)
    case `project_entry`(QueryResponseProjectEntry)
    case `promotion_preview`(QueryResponsePromotionPreview)
    case `search`(QueryResponseSearch)
    case `external_conversations`(QueryResponseExternalConversations)
}

public enum RecoveryAction {
    case `refresh_file`(RecoveryActionRefreshFile)
    case `refresh_conversation`(RecoveryActionRefreshConversation)
    case `refresh_run`(RecoveryActionRefreshRun)
    case `resume_events`(RecoveryActionResumeEvents)
}

public enum Registrability {
    case `registrable`(RegistrabilityRegistrable)
    case `not_a_repository`(RegistrabilityNotARepository)
    case `broken_repository`(RegistrabilityBrokenRepository)
    case `bare_repository`(RegistrabilityBareRepository)
    case `inside_git_dir`(RegistrabilityInsideGitDir)
    case `inside_working_tree`(RegistrabilityInsideWorkingTree)
}

public enum RemotePairingRequest {
    case `claim`(RemotePairingRequestClaim)
    case `complete`(RemotePairingRequestComplete)
}

public enum RemotePairingResponse {
    case `claimed`(RemotePairingResponseClaimed)
    case `completed`(RemotePairingResponseCompleted)
    case `rejected`(RemotePairingResponseRejected)
}

public struct Repository {
    public let `checkout`: Checkout
    public let `lfs`: ToolAvailability
    public let `submodules`: [GitLink]
    public let `worktree`: Worktree
}

public struct ResolvedSetting {
    public let `key`: SettingKey
    public let `source`: SettingSource
    public let `value`: SettingValue
}

public enum RestartMetadata {
    case `cursor_expired`(RestartMetadataCursorExpired)
    case `cursor_ahead`(RestartMetadataCursorAhead)
    case `pagination_stale`(RestartMetadataPaginationStale)
}

public enum RetentionPolicy: String {
    case `retain` = "retain"
    case `forget_after_final_run` = "forget_after_final_run"
}

public struct ReviewComment {
    public let `comment`: String
    public let `line`: UInt32
    public let `path`: String
}

public struct RevisionConflict {
    public let `current_revision`: String
    public let `safe_state`: ConflictState
}

public struct Run {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public enum RunActivity: String {
    case `working` = "working"
    case `waiting_for_user` = "waiting_for_user"
    case `waiting_for_approval` = "waiting_for_approval"
    case `waiting_for_auth` = "waiting_for_auth"
    case `waiting_for_quota` = "waiting_for_quota"
    case `reconnecting` = "reconnecting"
}

public enum RunControl: String {
    case `interrupt_turn` = "interrupt_turn"
    case `stop_run` = "stop_run"
}

public struct RunExecution {
    public let `activity`: RunActivity?
    public let `cursor`: String
    public let `exit_code`: Int32?
    public let `native_conversation`: String?
    public let `processes`: [ManagedProcess]
    public let `run`: Run
    public let `termination`: RunTermination?
}

public enum RunLifecycle: String {
    case `created` = "created"
    case `starting` = "starting"
    case `active` = "active"
    case `stopping` = "stopping"
    case `completed` = "completed"
    case `failed` = "failed"
    case `canceled` = "canceled"
    case `lost` = "lost"
}

public struct RunTermination {
    public let `control`: RunControl
    public let `stage`: TerminationStage
}

public struct ScheduleFiring {
    public let `due_at_unix_ms`: Int64
    public let `firing_id`: String
    public let `intended_local`: String
}

public struct ScheduledTask {
    public let `authorized_by`: String
    public let `conversation_id`: String
    public let `local_time`: String
    public let `next`: ScheduleFiring
    public let `prompt`: String
    public let `schedule_id`: String
    public let `time_zone`: String
}

public struct ScheduledTasks {
    public let `cursor`: String
    public let `tasks`: [ScheduledTask]
}

public enum SearchField: String {
    case `name` = "name"
    case `path` = "path"
    case `branch` = "branch"
}

public struct SearchHit {
    public let `conversation_id`: String
    public let `excerpt`: String
    public let `field`: SearchField
    public let `sequence`: String
}

public struct SearchResult {
    public let `cursor`: String
    public let `hits`: [SearchHit]
    public let `indexed_through`: String
}

public struct SecurityAudit {
    public let `cursor`: String
    public let `entries`: [AuditEntry]
}

public enum SecurityState {
    case `trusted`(SecurityStateTrusted)
    case `degraded`(SecurityStateDegraded)
}

public enum SeedSelection {
    case `none`(SeedSelectionNone)
    case `all_eligible`(SeedSelectionAllEligible)
    case `paths`(SeedSelectionPaths)
}

public enum ServerHello {
    case `challenge`(ServerHelloChallenge)
    case `welcome`(ServerHelloWelcome)
    case `rejected`(ServerHelloRejected)
}

public enum ServerMessage {
    case `terminal_attached`(ServerMessageTerminalAttached)
    case `terminal_resized`(ServerMessageTerminalResized)
    case `query_result`(ServerMessageQueryResult)
    case `command_result`(ServerMessageCommandResult)
    case `error`(ServerMessageError)
}

public enum SettingKey: String {
    case `utility.automatic_naming` = "utility.automatic_naming"
    case `git.auto_commit` = "git.auto_commit"
    case `git.message_instructions` = "git.message_instructions"
    case `security.audit_retention_days` = "security.audit_retention_days"
}

public enum SettingScope {
    case `plane`(SettingScopePlane)
    case `project`(SettingScopeProject)
    case `conversation`(SettingScopeConversation)
}

public enum SettingSelection {
    case `all`(SettingSelectionAll)
    case `key`(SettingSelectionKey)
}

public struct SettingSnapshot {
    public let `cursor`: String
    public let `scope`: SettingScope
    public let `settings`: [ResolvedSetting]
}

public enum SettingSource {
    case `built_in`(SettingSourceBuiltIn)
    case `scope`(SettingSourceScope)
}

public enum SettingValue {
    case `flag`(SettingValueFlag)
    case `text`(SettingValueText)
    case `count`(SettingValueCount)
}

public typealias Sha256Digest = String

public enum StreamControl {
    case `credit`(StreamControlCredit)
    case `terminal_gap`(StreamControlTerminalGap)
    case `terminal_finished`(StreamControlTerminalFinished)
    case `artifact_finished`(StreamControlArtifactFinished)
}

public enum TerminalState: String {
    case `opening` = "opening"
    case `open` = "open"
    case `closing` = "closing"
    case `closed` = "closed"
    case `unavailable` = "unavailable"
}

public enum TerminationStage: String {
    case `native_cancellation` = "native_cancellation"
    case `interrupt` = "interrupt"
    case `terminate` = "terminate"
    case `kill` = "kill"
    case `unobserved` = "unobserved"
}

public enum ToolAvailability {
    case `present`(ToolAvailabilityPresent)
    case `missing`(ToolAvailabilityMissing)
}

public struct Turn {
    public let `client_id`: String
    public let `run_id`: String?
    public let `sequence`: String
    public let `source`: TurnSource
    public let `state`: TurnState
    public let `turn_id`: String
}

public enum TurnOutcome: String {
    case `completed` = "completed"
    case `interrupted` = "interrupted"
}

public struct TurnQueue {
    public let `cursor`: String
    public let `turns`: [Turn]
}

public enum TurnSource: String {
    case `user` = "user"
    case `schedule` = "schedule"
    case `auto_continue` = "auto_continue"
}

public enum TurnState: String {
    case `queued` = "queued"
    case `active` = "active"
    case `completed` = "completed"
    case `superseded` = "superseded"
    case `canceled` = "canceled"
    case `withdrawn` = "withdrawn"
    case `failed` = "failed"
    case `outcome_unknown` = "outcome_unknown"
}

public struct VersionRange {
    public let `max`: UInt32
    public let `min`: UInt32
}

public struct WireError {
    public let `category`: ErrorCategory
    public let `code`: String
    public let `message`: String
    public let `recovery_actions`: [RecoveryAction]?
    public let `restart`: RestartMetadata?
    public let `retryable`: Bool
    public let `revision_conflict`: RevisionConflict?
}

public enum WorkingTree {
    case `no_project`(WorkingTreeNoProject)
    case `workspace`(WorkingTreeWorkspace)
    case `local_checkout`(WorkingTreeLocalCheckout)
}

public enum WorkingTreeRequest {
    case `no_project`(WorkingTreeRequestNoProject)
    case `workspace`(WorkingTreeRequestWorkspace)
    case `local_checkout`(WorkingTreeRequestLocalCheckout)
}

public struct Workspace {
    public let `base`: WorkspaceBase
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `project_id`: String
    public let `promotion`: WorkspacePromotion?
    public let `root`: String
    public let `seed`: WorkspaceSeed?
    public let `workspace_id`: String
}

public struct WorkspaceBase {
    public let `commit`: String
    public let `selection`: BaseSelection
}

public struct WorkspacePromotion {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `promotion_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `settled_at_unix_ms`: Int64?
    public let `state`: PromotionState
}

public struct WorkspaceSeed {
    public let `changed_paths`: UInt32
    public let `tree`: String
}

public struct WorkspaceTerminal {
    public let `state`: TerminalState
    public let `terminal_id`: String
    public let `workspace_id`: String
}

public enum Worktree {
    case `main`(WorktreeMain)
    case `linked`(WorktreeLinked)
}

public struct ActorInteractiveClient {
    public let `client_id`: String
}

public struct AuditBreachHeadMissing {

}

public struct AuditBreachHeadNotInStore {

}

public struct AuditBreachHeadDiverged {

}

public struct AuditBreachRecordAltered {
    public let `sequence`: String
}

public struct AuditBreachTargetAltered {
    public let `sequence`: String
}

public struct BaseSelectionHead {

}

public struct BaseSelectionRevision {
    public let `revision`: String
}

public struct CapabilityObservationLastObserved {

}

public struct CapabilityObservationFresh {

}

public struct ChangeOriginUserEdit {
    public let `client_id`: String
}

public struct ChangeOriginWorkspaceTerminal {
    public let `terminal_id`: String
}

public struct ChangeOriginHarness {
    public let `run_id`: String
}

public struct ChangeOriginMixed {

}

public struct ChangeOriginExternalOrUnknown {

}

public struct ClientMessageAttachTerminal {
    public let `after`: String
    public let `credit`: String
    public let `id`: UInt64
    public let `terminal_id`: String
}

public struct ClientMessageResizeTerminal {
    public let `columns`: Int64
    public let `id`: UInt64
    public let `rows`: Int64
}

public struct ClientMessageQuery {
    public let `id`: UInt64
    public let `query`: QueryRequest
    public let `timeout_ms`: UInt32?
}

public struct ClientMessageCommand {
    public let `command`: CommandRequest
    public let `command_id`: String
    public let `id`: UInt64
}

public struct CommandRequestCreateSchedule {
    public let `conversation_id`: String
    public let `local_time`: String
    public let `prompt`: String
    public let `time_zone`: String
}

public struct CommandRequestCancelSchedule {
    public let `schedule_id`: String
}

public struct CommandRequestApplyUserEdit {
    public let `content`: String
    public let `expected_revision`: FileRevision
    public let `path`: String
    public let `target`: FileTarget
}

public struct CommandRequestSubmitReview {
    public let `comments`: [ReviewComment]
    public let `conversation_id`: String
}

public struct CommandRequestSetConversationName {
    public let `conversation_id`: String
    public let `expected_revision`: String
    public let `name`: String
}

public struct CommandRequestSetRunName {
    public let `expected_revision`: String
    public let `name`: String
    public let `run_id`: String
}

public struct CommandRequestOpenTerminal {
    public let `columns`: Int64
    public let `rows`: Int64
    public let `workspace_id`: String
}

public struct CommandRequestCloseTerminal {
    public let `terminal_id`: String
}

public struct CommandRequestWithdrawTurn {
    public let `conversation_id`: String
    public let `turn_id`: String
}

public struct CommandRequestSubmitTurn {
    public let `conversation_id`: String
    public let `prompt`: String
    public let `source`: TurnSource?
}

public struct CommandRequestResolveExecution {
    public let `action`: ExecutionAction
    public let `execution_id`: String
    public let `instance`: String?
}

public struct CommandRequestInterruptTurn {
    public let `run_id`: String
}

public struct CommandRequestStopRun {
    public let `run_id`: String
}

public struct CommandRequestStartRun {
    public let `conversation_id`: String
    public let `craft`: String
    public let `prompt`: String
}

public struct CommandRequestCreateConversation {
    public let `retention`: RetentionPolicy?
    public let `working_tree`: WorkingTreeRequest?
}

public struct CommandRequestForkConversation {
    public let `checkpoint_turn`: UInt32
    public let `source_run_id`: String
}

public struct CommandRequestCreateRun {
    public let `conversation_id`: String
}

public struct CommandRequestSetSetting {
    public let `key`: SettingKey
    public let `scope`: SettingScope
    public let `value`: SettingValue
}

public struct CommandRequestClearSetting {
    public let `key`: SettingKey
    public let `scope`: SettingScope
}

public struct CommandRequestBindAccount {
    public let `credential_source`: CredentialSource
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct CommandRequestUnbindAccount {
    public let `binding_id`: String
}

public struct CommandRequestBeginAuditEpoch {

}

public struct CommandRequestSetPairingGate {
    public let `gate`: PairingGate
}

public struct CommandRequestOpenPairing {
    public let `method`: PairingMethod
}

public struct CommandRequestClaimPairing {
    public let `key`: ClientPublicKey
    public let `secret`: String
}

public struct CommandRequestConfirmPairing {
    public let `authentication_string`: String
    public let `offer_id`: String
}

public struct CommandRequestCompletePairing {
    public let `offer_id`: String
    public let `signature`: String
}

public struct CommandRequestSetPairedClientAccess {
    public let `access`: PairedClientAccess
    public let `client_id`: String
}

public struct CommandRequestRevokePairedClient {
    public let `client_id`: String
}

public struct CommandRequestTransitionRun {
    public let `expected_revision`: String
    public let `lifecycle`: RunLifecycle
    public let `run_id`: String
}

public struct CommandRequestRegisterProject {
    public let `path`: String
}

public struct CommandRequestPromoteWorkspace {
    public let `binding`: PromotionBinding
}

public struct CommandRequestImportConversation {
    public let `harness`: String
    public let `native_conversation`: String
}

public struct CommandRequestResumeImportedConversation {
    public let `import_id`: String
    public let `retention`: RetentionPolicy?
    public let `working_tree`: WorkingTreeRequest
}

public struct CommandResponseScheduleCreated {
    public let `task`: ScheduledTask
}

public struct CommandResponseScheduleCanceled {
    public let `schedule_id`: String
}

public struct CommandResponseUserEditApplied {
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public struct CommandResponseConversationNamed {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct CommandResponseRunNamed {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseTerminal {
    public let `terminal`: WorkspaceTerminal
}

public struct CommandResponseTurnWithdrawn {
    public let `turn`: Turn
}

public struct CommandResponseTurnAdmitted {
    public let `turn`: Turn
}

public struct CommandResponseRunControlAccepted {
    public let `control`: RunControl
    public let `run`: Run
}

public struct CommandResponseExecutionResolutionRecorded {
    public let `action`: ExecutionAction
    public let `execution_id`: String
}

public struct CommandResponseConversationCreated {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct CommandResponseRunCreated {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseRunTransitioned {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseSettingSet {
    public let `key`: SettingKey
    public let `scope`: SettingScope
    public let `value`: SettingValue
}

public struct CommandResponseSettingCleared {
    public let `key`: SettingKey
    public let `scope`: SettingScope
}

public struct CommandResponseAccountBound {
    public let `binding_id`: String
    public let `created_at_unix_ms`: Int64
    public let `credential_reference`: CredentialReference
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct CommandResponseAccountUnbound {
    public let `binding_id`: String
    public let `credential_reference`: CredentialReference
}

public struct CommandResponsePairingGateSet {
    public let `gate`: PairingGate
}

public struct CommandResponsePairingOpened {
    public let `disclosure`: PairingDisclosure
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingClaimed {
    public let `challenge`: String
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingConfirmed {
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingCompleted {
    public let `client`: PairedClient
}

public struct CommandResponsePairedClientAccessSet {
    public let `client`: PairedClient
}

public struct CommandResponsePairedClientRevoked {
    public let `client_id`: String
}

public struct CommandResponseAuditEpochBegun {
    public let `epoch`: String
}

public struct CommandResponseProjectRegistered {
    public let `project_id`: String
    public let `registered_at_unix_ms`: Int64
    public let `registered_by`: Actor
    public let `root`: String
}

public struct CommandResponseWorkspacePromotionRecorded {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `promotion_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `settled_at_unix_ms`: Int64?
    public let `state`: PromotionState
}

public struct CommandResponseConversationImported {
    public let `harness`: String
    public let `import_id`: String
    public let `imported_at_unix_ms`: Int64
    public let `imported_by`: Actor
    public let `native_conversation`: String
    public let `resumed_as`: String?
    public let `working_directory`: String?
}

public struct ConflictStateConversation {
    public let `conversation`: Conversation
}

public struct ConflictStateRun {
    public let `run`: Run
}

public struct ConversationOriginNew {

}

public struct ConversationOriginImported {
    public let `import_id`: String
}

public struct ConversationOriginForked {
    public let `checkpoint_turn`: UInt32
    public let `source_conversation_id`: String
    public let `source_run_id`: String
}

public struct CredentialReferencePlatformStore {
    public let `item`: CredentialItem
}

public struct CredentialReferenceExternalHelper {
    public let `helper`: String
}

public struct CredentialReferenceHarnessNative {

}

public struct CredentialReferenceSessionOnly {
    public let `established_at_daemon_start`: UInt64
}

public struct CredentialSourcePlatformStore {

}

public struct CredentialSourceExternalHelper {
    public let `helper`: String
}

public struct CredentialSourceHarnessNative {

}

public struct CredentialSourceSessionOnly {

}

public struct CredentialStateResolvable {

}

public struct CredentialStateResolvedAtUse {

}

public struct CredentialStateWaitingForUnlock {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStateUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStateInvalidatedByRestart {

}

public struct CredentialStoreStatusAvailable {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStoreStatusLocked {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStoreStatusUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct DegradedConditionMissingExternalTool {
    public let `tool`: ExternalTool
}

public struct DegradedConditionNoHarnessAvailable {

}

public struct DegradedConditionCredentialStoreUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct DegradedConditionCredentialStoreLocked {
    public let `kind`: CredentialStoreKind
}

public struct DiffScopeCurrent {

}

public struct DiffScopeFinal {

}

public struct DiffScopeHistorical {
    public let `from_turn`: UInt32
    public let `to_turn`: UInt32
}

public struct DiffScopeTurn {
    public let `turn`: UInt32
}

public struct EntryKindFile {
    public let `bytes`: UInt64
}

public struct EntryKindDirectory {

}

public struct EntryKindOther {

}

public struct EntryKindMissing {

}

public struct EventOriginScheduledTask {
    public let `schedule_id`: String
}

public struct EventOriginHarness {
    public let `run_id`: String
}

public struct EventOriginRunSupervisor {
    public let `run_id`: String
}

public struct ExternalOriginProject {
    public let `project_id`: String
    public let `working_directory`: String
}

public struct ExternalOriginUnregistered {
    public let `working_directory`: String
}

public struct ExternalOriginUnknown {

}

public struct ExternalProcessNone {

}

public struct ExternalProcessExternal {
    public let `pid`: UInt32
}

public struct ExternalProcessCooperating {
    public let `endpoint`: String
    public let `pid`: UInt32
}

public struct FileTargetProject {
    public let `project_id`: String
}

public struct FileTargetWorkspace {
    public let `workspace_id`: String
}

public struct PairingDisclosureManualCode {
    public let `code`: String
}

public struct PairingDisclosureQrPayload {
    public let `payload`: String
}

public struct PairingDisclosureAlreadyDisclosed {

}

public struct PairingMethodManualCode {

}

public struct PairingMethodQrPayload {
    public let `endpoint`: String
}

public struct PairingProgressOffered {

}

public struct PairingProgressAwaitingConfirmation {
    public let `authentication_string`: String
    public let `client_id`: String
}

public struct PairingProgressConfirmed {
    public let `authentication_string`: String
    public let `client_id`: String
}

public struct PairingProgressEnded {
    public let `reason`: PairingEnd
}

public struct PromotionDestinationLocalCheckout {

}

public struct PromotionDestinationBranch {
    public let `name`: String
}

public struct QueryRequestScheduledTasks {
    public let `conversation_id`: String
}

public struct QueryRequestEditableFile {
    public let `path`: String
    public let `target`: FileTarget
}

public struct QueryRequestWorkspaceTerminals {
    public let `workspace_id`: String
}

public struct QueryRequestChangeArtifact {
    public let `offset`: String
    public let `sha256`: String
}

public struct QueryRequestChangeDiff {
    public let `run_id`: String
    public let `scope`: DiffScope
}

public struct QueryRequestNextChangeDiff {
    public let `cursor`: PageCursor
}

public struct QueryRequestTurnQueue {
    public let `conversation_id`: String
}

public struct QueryRequestOrphanedExecutions {
    public let `after`: String?
}

public struct QueryRequestRunExecution {
    public let `run_id`: String
}

public struct QueryRequestStatus {

}

public struct QueryRequestConversations {

}

public struct QueryRequestNextConversations {
    public let `cursor`: PageCursor
}

public struct QueryRequestConversation {
    public let `conversation_id`: String
}

public struct QueryRequestCapabilities {
    public let `observation`: CapabilityObservation
}

public struct QueryRequestAccountBindings {
    public let `observation`: CapabilityObservation
}

public struct QueryRequestSettings {
    public let `scope`: SettingScope
    public let `selection`: SettingSelection
}

public struct QueryRequestEvents {
    public let `after`: String
}

public struct QueryRequestPairing {

}

public struct QueryRequestSecurityAudit {
    public let `after`: String
}

public struct QueryRequestProjects {

}

public struct QueryRequestPreviewProject {
    public let `observation`: CapabilityObservation
    public let `path`: String
}

public struct QueryRequestProjectEntry {
    public let `path`: String
    public let `project_id`: String
}

public struct QueryRequestPreviewPromotion {
    public let `destination`: PromotionDestination
    public let `workspace_id`: String
}

public struct QueryRequestSearch {
    public let `text`: String
}

public struct QueryRequestExternalConversations {

}

public struct QueryResponseScheduledTasks {
    public let `cursor`: String
    public let `tasks`: [ScheduledTask]
}

public struct QueryResponseEditableFile {
    public let `content`: String?
    public let `cursor`: String
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public struct QueryResponseWorkspaceTerminals {
    public let `cursor`: String
    public let `terminals`: [WorkspaceTerminal]
}

public struct QueryResponseChangeArtifact {
    public let `artifact`: ChangeArtifact
    public let `bytes`: [Int64]
    public let `offset`: String
}

public struct QueryResponseChangeDiff {
    public let `after`: ChangeSnapshot
    public let `artifact`: ChangeArtifact
    public let `before`: ChangeSnapshot
    public let `cursor`: String
    public let `files`: [ChangedFile]
    public let `latest_turn`: UInt32
    public let `next_page`: PageCursor?
    public let `outcome`: TurnOutcome?
    public let `patch`: String
    public let `patch_truncated`: Bool
    public let `plane_id`: String
    public let `run_id`: String
    public let `scope`: DiffScope
    public let `total_files`: UInt32
    public let `workspace_id`: String?
}

public struct QueryResponseTurnQueue {
    public let `cursor`: String
    public let `turns`: [Turn]
}

public struct QueryResponseOrphanedExecutions {
    public let `executions`: [OrphanedExecution]
    public let `next`: String?
}

public struct QueryResponseRunExecution {
    public let `activity`: RunActivity?
    public let `cursor`: String
    public let `exit_code`: Int32?
    public let `native_conversation`: String?
    public let `processes`: [ManagedProcess]
    public let `run`: Run
    public let `termination`: RunTermination?
}

public struct QueryResponseStatus {
    public let `core_version`: String
    public let `cursor`: String?
    public let `daemon_starts`: UInt64
    public let `plane_id`: String
    public let `security`: SecurityState?
    public let `started_at_unix_ms`: Int64
}

public struct QueryResponseConversations {
    public let `conversations`: [Conversation]
    public let `cursor`: String
    public let `next_page`: PageCursor?
}

public struct QueryResponseConversation {
    public let `conversation`: Conversation
    public let `cursor`: String
    public let `runs`: [Run]
    public let `workspace`: Workspace?
}

public struct QueryResponseCapabilities {
    public let `core_version`: String
    public let `crafts`: [InstalledCraft]
    public let `credential_store`: CredentialStoreStatus
    public let `degraded`: [DegradedCondition]
    public let `external_tools`: [ExternalToolStatus]
    public let `harnesses`: [String]
    public let `observed_at_unix_ms`: Int64
    public let `platform`: Platform
}

public struct QueryResponseAccountBindings {
    public let `bindings`: [AccountBindingStatus]
    public let `cursor`: String
}

public struct QueryResponseSettings {
    public let `cursor`: String
    public let `scope`: SettingScope
    public let `settings`: [ResolvedSetting]
}

public struct QueryResponseEvents {
    public let `cursor`: String
    public let `events`: [Event]
}

public struct QueryResponsePairing {
    public let `clients`: [PairedClient]?
    public let `cursor`: String
    public let `gate`: PairingGate
    public let `pending`: PendingPairing?
}

public struct QueryResponseSecurityAudit {
    public let `cursor`: String
    public let `entries`: [AuditEntry]
}

public struct QueryResponseProjects {
    public let `cursor`: String
    public let `projects`: [Project]
}

public struct QueryResponseProjectPreview {
    public let `registrability`: Registrability
    public let `root`: String
}

public struct QueryResponseProjectEntry {
    public let `cursor`: String
    public let `kind`: EntryKind
    public let `path`: String
    public let `project_id`: String
}

public struct QueryResponsePromotionPreview {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `changes`: [PromotedChange]
    public let `cursor`: String
}

public struct QueryResponseSearch {
    public let `cursor`: String
    public let `hits`: [SearchHit]
    public let `indexed_through`: String
}

public struct QueryResponseExternalConversations {
    public let `cursor`: String
    public let `discovered`: [ExternalConversation]
    public let `imported`: [ImportedConversation]
}

public struct RecoveryActionRefreshFile {
    public let `current_revision`: FileRevision
    public let `path`: String
    public let `target`: FileTarget
}

public struct RecoveryActionRefreshConversation {
    public let `conversation_id`: String
}

public struct RecoveryActionRefreshRun {
    public let `run_id`: String
}

public struct RecoveryActionResumeEvents {
    public let `after`: String
}

public struct RegistrabilityRegistrable {
    public let `repository`: Repository
}

public struct RegistrabilityNotARepository {

}

public struct RegistrabilityBrokenRepository {

}

public struct RegistrabilityBareRepository {

}

public struct RegistrabilityInsideGitDir {

}

public struct RegistrabilityInsideWorkingTree {
    public let `toplevel`: String
}

public struct RemotePairingRequestClaim {
    public let `command_id`: String
    public let `key`: ClientPublicKey
    public let `secret`: String
}

public struct RemotePairingRequestComplete {
    public let `command_id`: String
    public let `offer_id`: String
    public let `signature`: String
}

public struct RemotePairingResponseClaimed {
    public let `pending`: PendingPairing
    public let `signing_bytes`: [Int64]
}

public struct RemotePairingResponseCompleted {
    public let `client`: PairedClient
}

public struct RemotePairingResponseRejected {
    public let `error`: WireError
}

public struct RestartMetadataCursorExpired {
    public let `current_snapshot_revision`: String
    public let `minimum_available_cursor`: String
}

public struct RestartMetadataCursorAhead {
    public let `current_snapshot_revision`: String
}

public struct RestartMetadataPaginationStale {
    public let `current_snapshot_revision`: String
}

public struct SecurityStateTrusted {

}

public struct SecurityStateDegraded {
    public let `breach`: AuditBreach
    public let `epoch`: String
    public let `head`: AuditHead?
    public let `store_sequence`: String
}

public struct SeedSelectionNone {

}

public struct SeedSelectionAllEligible {

}

public struct SeedSelectionPaths {
    public let `paths`: [String]
}

public struct ServerHelloChallenge {
    public let `nonce`: String
}

public struct ServerHelloWelcome {
    public let `capabilities`: [String]?
    public let `codec`: String
    public let `max_control_frame`: UInt32
    public let `max_data_frame`: UInt32
    public let `minor`: UInt32
    public let `protocol`: UInt32
}

public struct ServerHelloRejected {
    public let `error`: WireError
}

public struct ServerMessageTerminalAttached {
    public let `id`: UInt64
}

public struct ServerMessageTerminalResized {
    public let `id`: UInt64
}

public struct ServerMessageQueryResult {
    public let `id`: UInt64
    public let `result`: QueryResponse
}

public struct ServerMessageCommandResult {
    public let `id`: UInt64
    public let `result`: CommandResponse
}

public struct ServerMessageError {
    public let `error`: WireError
    public let `id`: UInt64?
}

public struct SettingScopePlane {

}

public struct SettingScopeProject {
    public let `project_id`: String
}

public struct SettingScopeConversation {
    public let `conversation_id`: String
}

public struct SettingSelectionAll {

}

public struct SettingSelectionKey {
    public let `key`: SettingKey
}

public struct SettingSourceBuiltIn {

}

public struct SettingSourceScope {
    public let `scope`: SettingScope
}

public struct SettingValueFlag {
    public let `value`: Bool
}

public struct SettingValueText {
    public let `value`: String
}

public struct SettingValueCount {
    public let `value`: UInt32
}

public struct StreamControlCredit {
    public let `bytes`: UInt64
}

public struct StreamControlTerminalGap {
    public let `first_missing_offset`: String
    public let `missing_bytes`: String
}

public struct StreamControlTerminalFinished {
    public let `total_bytes`: String
}

public struct StreamControlArtifactFinished {
    public let `sha256`: Sha256Digest
    public let `total_bytes`: String
}

public struct ToolAvailabilityPresent {
    public let `version`: String
}

public struct ToolAvailabilityMissing {

}

public struct WorkingTreeNoProject {

}

public struct WorkingTreeWorkspace {
    public let `project_id`: String
}

public struct WorkingTreeLocalCheckout {
    public let `project_id`: String
}

public struct WorkingTreeRequestNoProject {

}

public struct WorkingTreeRequestWorkspace {
    public let `base`: BaseSelection?
    public let `project_id`: String
    public let `seed`: SeedSelection?
}

public struct WorkingTreeRequestLocalCheckout {
    public let `project_id`: String
}

public struct WorktreeMain {

}

public struct WorktreeLinked {
    public let `common_dir`: String
}
