// Generated by just contracts. Do not edit.
// Models only: validate against the schema and retain raw JSON before decoding.


public struct RawJSON { public let source: String }

public struct AccountBinding {
    public let `binding_id`: String
    public let `created_at_unix_ms`: Int64
    public let `credential_reference`: CredentialReference
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct AccountBindingList {
    public let `bindings`: [AccountBindingStatus]
    public let `cursor`: String
}

public struct AccountBindingStatus {
    public let `binding`: AccountBinding
    public let `credential_state`: CredentialState
}

public enum Actor {
    case `interactive_client`(ActorInteractiveClient)
}

public enum ArtifactAvailability: String {
    case `disk_pressure` = "disk_pressure"
    case `stored` = "stored"
    case `run_budget_exceeded` = "run_budget_exceeded"
    case `artifact_size_exceeded` = "artifact_size_exceeded"
}

public enum ArtifactControl {
    case `artifact_upload`(ArtifactControlArtifactUpload)
    case `artifact_commit`(ArtifactControlArtifactCommit)
    case `artifact_published`(ArtifactControlArtifactPublished)
    case `artifact_download`(ArtifactControlArtifactDownload)
    case `artifact_downloading`(ArtifactControlArtifactDownloading)
    case `artifact_cancel`(ArtifactControlArtifactCancel)
    case `artifact_canceled`(ArtifactControlArtifactCanceled)
    case `artifact_collect`(ArtifactControlArtifactCollect)
    case `artifact_collected`(ArtifactControlArtifactCollected)
}

public struct ArtifactDescriptor {
    public let `sha256`: Sha256Digest
    public let `size`: String
}

public enum AuditActor {
    case `interactive_client`(AuditActorInteractiveClient)
    case `craft_revocation`(AuditActorCraftRevocation)
}

public enum AuditBreach {
    case `head_missing`(AuditBreachHeadMissing)
    case `head_not_in_store`(AuditBreachHeadNotInStore)
    case `head_diverged`(AuditBreachHeadDiverged)
    case `record_altered`(AuditBreachRecordAltered)
    case `target_altered`(AuditBreachTargetAltered)
}

public struct AuditEntry {
    public let `actor`: AuditActor
    public let `decision`: String
    public let `epoch`: String
    public let `outcome`: AuditOutcome
    public let `plane_id`: String
    public let `record_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `risk`: AuditRisk
    public let `sequence`: String
    public let `target`: AuditTarget
}

public struct AuditHead {
    public let `entry_hash`: String
    public let `epoch`: String
    public let `sequence`: String
}

public enum AuditOutcome: String {
    case `succeeded` = "succeeded"
    case `denied` = "denied"
    case `failed` = "failed"
}

public enum AuditRisk: String {
    case `routine` = "routine"
    case `elevated` = "elevated"
    case `destructive` = "destructive"
}

public struct AuditTarget {
    public let `identity`: String?
    public let `kind`: String
    public let `reference`: String
}

public enum AutoContinuePolicy {
    case `off`(AutoContinuePolicyOff)
    case `retry`(AutoContinuePolicyRetry)
}

public struct AutoContinueRetry {
    public let `due_at_unix_ms`: Int64
    public let `observed_at_unix_ms`: Int64
    public let `policy`: AutoContinuePolicy
    public let `retry_count`: UInt32
    public let `retry_turn`: String?
    public let `run_id`: String
    public let `selected_from`: AutoContinueTarget
    public let `status`: AutoContinueStatus
    public let `triggering_turn`: String
    public let `usage`: AutoContinueUsage
}

public struct AutoContinueSnapshot {
    public let `cursor`: String
    public let `policy`: AutoContinuePolicy
    public let `retry`: AutoContinueRetry?
}

public enum AutoContinueStatus: String {
    case `disabled` = "disabled"
    case `deferred` = "deferred"
    case `pending` = "pending"
    case `dispatched` = "dispatched"
    case `canceled` = "canceled"
    case `exhausted` = "exhausted"
}

public enum AutoContinueTarget {
    case `variant0`(AutoContinueTargetVariant0)
    case `variant1`(AutoContinueTargetVariant1)
}

public struct AutoContinueUsage {
    public let `estimation`: UsageEstimation
    public let `finality`: UsageFinality
    public let `measure`: QuotaMeasure
    public let `resets_in_seconds`: UInt64?
    public let `scope`: QuotaScope
    public let `window`: String
    public let `window_seconds`: UInt64?
}

public enum BaseSelection {
    case `head`(BaseSelectionHead)
    case `revision`(BaseSelectionRevision)
}

public enum BrokerPermission: String {
    case `artifact_read` = "artifact_read"
    case `artifact_write` = "artifact_write"
    case `remote_tools` = "remote_tools"
}

public enum CapabilityObservation {
    case `last_observed`(CapabilityObservationLastObserved)
    case `fresh`(CapabilityObservationFresh)
}

public struct CapabilitySnapshot {
    public let `core_version`: String
    public let `crafts`: [InstalledCraft]
    public let `credential_store`: CredentialStoreStatus
    public let `degraded`: [DegradedCondition]
    public let `external_tools`: [ExternalToolStatus]
    public let `harnesses`: [String]
    public let `observed_at_unix_ms`: Int64
    public let `platform`: Platform
    public let `resource_budgets`: ResourceBudgets?
}

public struct ChangeArtifact {
    public let `availability`: ArtifactAvailability?
    public let `sha256`: String
    public let `size`: UInt64
}

public struct ChangeArtifactChunk {
    public let `artifact`: ChangeArtifact
    public let `bytes`: [Int64]
    public let `offset`: String
}

public struct ChangeDiff {
    public let `after`: ChangeSnapshot
    public let `artifact`: ChangeArtifact
    public let `before`: ChangeSnapshot
    public let `cursor`: String
    public let `files`: [ChangedFile]
    public let `latest_turn`: UInt32
    public let `next_page`: PageCursor?
    public let `outcome`: TurnOutcome?
    public let `patch`: String
    public let `patch_truncated`: Bool
    public let `plane_id`: String
    public let `run_id`: String
    public let `scope`: DiffScope
    public let `total_files`: UInt32
    public let `workspace_id`: String?
}

public enum ChangeKind: String {
    case `added` = "added"
    case `modified` = "modified"
    case `deleted` = "deleted"
}

public enum ChangeOrigin {
    case `user_edit`(ChangeOriginUserEdit)
    case `workspace_terminal`(ChangeOriginWorkspaceTerminal)
    case `harness`(ChangeOriginHarness)
    case `mixed`(ChangeOriginMixed)
    case `external_or_unknown`(ChangeOriginExternalOrUnknown)
}

public struct ChangeSnapshot {
    public let `commit`: String
    public let `content_complete`: Bool
    public let `tree`: String
    public let `uncommitted`: ChangeArtifact
}

public struct ChangedFile {
    public let `after_mode`: String
    public let `after_object`: String?
    public let `after_size`: UInt64?
    public let `before_mode`: String
    public let `before_object`: String?
    public let `before_size`: UInt64?
    public let `origin`: ChangeOrigin
    public let `path`: String
}

public enum Checkout: String {
    case `full` = "full"
    case `sparse` = "sparse"
}

public struct ClientHello {
    public let `capabilities`: [String]?
    public let `client_id`: String
    public let `codec`: String
    public let `max_control_frame`: UInt32
    public let `max_data_frame`: UInt32
    public let `minor`: UInt32
    public let `protocol`: VersionRange
}

public enum ClientMessage {
    case `remote_tool`(ClientMessageRemoteTool)
    case `attach_terminal`(ClientMessageAttachTerminal)
    case `resize_terminal`(ClientMessageResizeTerminal)
    case `query`(ClientMessageQuery)
    case `command`(ClientMessageCommand)
}

public struct ClientPublicKey {
    public let `algorithm`: PairingKeyAlgorithm
    public let `key`: String
}

public enum CommandRequest {
    case `acknowledge_git_delivery`(CommandRequestAcknowledgeGitDelivery)
    case `deliver_git`(CommandRequestDeliverGit)
    case `set_auto_continue`(CommandRequestSetAutoContinue)
    case `authorize_approval_retry`(CommandRequestAuthorizeApprovalRetry)
    case `change_extension`(CommandRequestChangeExtension)
    case `review_remote_tool`(CommandRequestReviewRemoteTool)
    case `request_utility`(CommandRequestRequestUtility)
    case `disable_craft`(CommandRequestDisableCraft)
    case `install_craft`(CommandRequestInstallCraft)
    case `create_schedule`(CommandRequestCreateSchedule)
    case `cancel_schedule`(CommandRequestCancelSchedule)
    case `apply_user_edit`(CommandRequestApplyUserEdit)
    case `submit_review`(CommandRequestSubmitReview)
    case `set_conversation_name`(CommandRequestSetConversationName)
    case `set_run_name`(CommandRequestSetRunName)
    case `open_terminal`(CommandRequestOpenTerminal)
    case `close_terminal`(CommandRequestCloseTerminal)
    case `withdraw_turn`(CommandRequestWithdrawTurn)
    case `submit_turn`(CommandRequestSubmitTurn)
    case `resolve_execution`(CommandRequestResolveExecution)
    case `interrupt_turn`(CommandRequestInterruptTurn)
    case `stop_run`(CommandRequestStopRun)
    case `start_visa_run`(CommandRequestStartVisaRun)
    case `start_no_visa_run`(CommandRequestStartNoVisaRun)
    case `start_run`(CommandRequestStartRun)
    case `create_conversation`(CommandRequestCreateConversation)
    case `handoff_conversation`(CommandRequestHandoffConversation)
    case `fork_conversation`(CommandRequestForkConversation)
    case `create_run`(CommandRequestCreateRun)
    case `set_setting`(CommandRequestSetSetting)
    case `clear_setting`(CommandRequestClearSetting)
    case `bind_account`(CommandRequestBindAccount)
    case `unbind_account`(CommandRequestUnbindAccount)
    case `begin_audit_epoch`(CommandRequestBeginAuditEpoch)
    case `set_pairing_gate`(CommandRequestSetPairingGate)
    case `open_pairing`(CommandRequestOpenPairing)
    case `claim_pairing`(CommandRequestClaimPairing)
    case `confirm_pairing`(CommandRequestConfirmPairing)
    case `complete_pairing`(CommandRequestCompletePairing)
    case `set_paired_client_access`(CommandRequestSetPairedClientAccess)
    case `revoke_paired_client`(CommandRequestRevokePairedClient)
    case `transition_run`(CommandRequestTransitionRun)
    case `register_project`(CommandRequestRegisterProject)
    case `promote_workspace`(CommandRequestPromoteWorkspace)
    case `import_conversation`(CommandRequestImportConversation)
    case `resume_imported_conversation`(CommandRequestResumeImportedConversation)
}

public enum CommandResponse {
    case `git_delivery_acknowledged`(CommandResponseGitDeliveryAcknowledged)
    case `git_delivery_queued`(CommandResponseGitDeliveryQueued)
    case `auto_continue_configured`(CommandResponseAutoContinueConfigured)
    case `approval_retry_authorized`(CommandResponseApprovalRetryAuthorized)
    case `extension_change_queued`(CommandResponseExtensionChangeQueued)
    case `remote_tool_reviewed`(CommandResponseRemoteToolReviewed)
    case `utility_queued`(CommandResponseUtilityQueued)
    case `craft_disabled`(CommandResponseCraftDisabled)
    case `craft_installation_queued`(CommandResponseCraftInstallationQueued)
    case `schedule_created`(CommandResponseScheduleCreated)
    case `schedule_canceled`(CommandResponseScheduleCanceled)
    case `user_edit_applied`(CommandResponseUserEditApplied)
    case `conversation_named`(CommandResponseConversationNamed)
    case `run_named`(CommandResponseRunNamed)
    case `terminal`(CommandResponseTerminal)
    case `turn_withdrawn`(CommandResponseTurnWithdrawn)
    case `turn_admitted`(CommandResponseTurnAdmitted)
    case `run_control_accepted`(CommandResponseRunControlAccepted)
    case `execution_resolution_recorded`(CommandResponseExecutionResolutionRecorded)
    case `conversation_created`(CommandResponseConversationCreated)
    case `run_created`(CommandResponseRunCreated)
    case `run_transitioned`(CommandResponseRunTransitioned)
    case `setting_set`(CommandResponseSettingSet)
    case `setting_cleared`(CommandResponseSettingCleared)
    case `account_bound`(CommandResponseAccountBound)
    case `account_unbound`(CommandResponseAccountUnbound)
    case `pairing_gate_set`(CommandResponsePairingGateSet)
    case `pairing_opened`(CommandResponsePairingOpened)
    case `pairing_claimed`(CommandResponsePairingClaimed)
    case `pairing_confirmed`(CommandResponsePairingConfirmed)
    case `pairing_completed`(CommandResponsePairingCompleted)
    case `paired_client_access_set`(CommandResponsePairedClientAccessSet)
    case `paired_client_revoked`(CommandResponsePairedClientRevoked)
    case `audit_epoch_begun`(CommandResponseAuditEpochBegun)
    case `project_registered`(CommandResponseProjectRegistered)
    case `workspace_promotion_recorded`(CommandResponseWorkspacePromotionRecorded)
    case `conversation_imported`(CommandResponseConversationImported)
}

public enum ConflictKind: String {
    case `diverged` = "diverged"
    case `untracked` = "untracked"
    case `staged` = "staged"
}

public enum ConflictState {
    case `conversation`(ConflictStateConversation)
    case `run`(ConflictStateRun)
}

public struct ConnectionProof {
    public let `signature`: String
}

public struct Conversation {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct ConversationList {
    public let `conversations`: [Conversation]
    public let `cursor`: String
    public let `next_page`: PageCursor?
}

public enum ConversationOrigin {
    case `new`(ConversationOriginNew)
    case `imported`(ConversationOriginImported)
    case `forked`(ConversationOriginForked)
}

public struct ConversationSnapshot {
    public let `conversation`: Conversation
    public let `cursor`: String
    public let `runs`: [Run]
    public let `workspace`: Workspace?
}

public enum CraftDisableMode: String {
    case `wait` = "wait"
    case `force` = "force"
}

public enum CraftHostAccess {
    case `executable`(CraftHostAccessExecutable)
    case `filesystem`(CraftHostAccessFilesystem)
    case `environment`(CraftHostAccessEnvironment)
    case `network`(CraftHostAccessNetwork)
}

public struct CraftInstallationConfirmation {
    public let `artifact_sha256`: String
    public let `broker_permissions`: [BrokerPermission]
    public let `commit`: String
    public let `host_access`: [CraftHostAccess]
    public let `publisher_claim`: String
    public let `repository`: String
    public let `source`: CraftSource
    public let `trust`: CraftTrust
}

public struct CraftInstallationPreview {
    public let `confirmation`: CraftInstallationConfirmation
    public let `craft_id`: String
    public let `enabled_features`: [String]
    public let `version`: String
}

public struct CraftInstallationQueued {
    public let `artifact_sha256`: String
    public let `craft_id`: String
    public let `version`: String
}

public enum CraftSource {
    case `github_release`(CraftSourceGithubRelease)
    case `local`(CraftSourceLocal)
}

public enum CraftTrust: String {
    case `same_user_executable` = "same_user_executable"
    case `developer_source` = "developer_source"
}

public struct CredentialItem {
    public let `account`: String
    public let `service`: String
}

public enum CredentialReference {
    case `platform_store`(CredentialReferencePlatformStore)
    case `external_helper`(CredentialReferenceExternalHelper)
    case `harness_native`(CredentialReferenceHarnessNative)
    case `session_only`(CredentialReferenceSessionOnly)
}

public enum CredentialSource {
    case `platform_store`(CredentialSourcePlatformStore)
    case `external_helper`(CredentialSourceExternalHelper)
    case `harness_native`(CredentialSourceHarnessNative)
    case `session_only`(CredentialSourceSessionOnly)
}

public enum CredentialState {
    case `resolvable`(CredentialStateResolvable)
    case `resolved_at_use`(CredentialStateResolvedAtUse)
    case `waiting_for_unlock`(CredentialStateWaitingForUnlock)
    case `unavailable`(CredentialStateUnavailable)
    case `invalidated_by_restart`(CredentialStateInvalidatedByRestart)
}

public enum CredentialStoreKind: String {
    case `apple_keychain` = "apple_keychain"
    case `secret_service` = "secret_service"
}

public enum CredentialStoreStatus {
    case `available`(CredentialStoreStatusAvailable)
    case `locked`(CredentialStoreStatusLocked)
    case `unavailable`(CredentialStoreStatusUnavailable)
}

public enum DegradedCondition {
    case `missing_external_tool`(DegradedConditionMissingExternalTool)
    case `no_harness_available`(DegradedConditionNoHarnessAvailable)
    case `credential_store_unavailable`(DegradedConditionCredentialStoreUnavailable)
    case `credential_store_locked`(DegradedConditionCredentialStoreLocked)
}

public enum DiffScope {
    case `current`(DiffScopeCurrent)
    case `final`(DiffScopeFinal)
    case `historical`(DiffScopeHistorical)
    case `turn`(DiffScopeTurn)
}

public struct EditableFile {
    public let `content`: String?
    public let `cursor`: String
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public enum EntryKind {
    case `file`(EntryKindFile)
    case `directory`(EntryKindDirectory)
    case `other`(EntryKindOther)
    case `missing`(EntryKindMissing)
}

public enum ErrorCategory: String {
    case `invalid_input` = "invalid_input"
    case `unauthorized` = "unauthorized"
    case `conflict` = "conflict"
    case `unavailable` = "unavailable"
    case `incompatible` = "incompatible"
    case `rate_limited` = "rate_limited"
    case `not_found` = "not_found"
    case `outcome_unknown` = "outcome_unknown"
    case `internal` = "internal"
}

public struct Event {
    public let `actor`: Actor
    public let `conversation_id`: String?
    public let `event_id`: String
    public let `kind`: String
    public let `origin`: EventOrigin?
    public let `payload`: RawJSON
    public let `payload_version`: UInt32
    public let `recorded_at_unix_ms`: Int64
    public let `run_id`: String?
    public let `sequence`: String
}

public enum EventOrigin {
    case `auto_continue`(EventOriginAutoContinue)
    case `scheduled_task`(EventOriginScheduledTask)
    case `harness`(EventOriginHarness)
    case `run_supervisor`(EventOriginRunSupervisor)
}

public struct EventPage {
    public let `cursor`: String
    public let `events`: [Event]
}

public enum ExecutionAction: String {
    case `adopt` = "adopt"
    case `leave` = "leave"
    case `terminate` = "terminate"
}

public struct ExecutionMetadata {
    public let `helper_pid`: UInt32
    public let `instance`: String
    public let `project_root`: String
    public let `root`: String
    public let `version`: String
}

public enum ExecutionRole: String {
    case `run` = "run"
    case `terminal` = "terminal"
}

public enum ExtensionAction: String {
    case `install` = "install"
    case `update` = "update"
    case `disable` = "disable"
    case `remove` = "remove"
}

public struct ExtensionCatalog {
    public let `craft_id`: String
    public let `harness`: String
    public let `native_metadata`: String
}

public struct ExtensionChange {
    public let `action`: ExtensionAction
    public let `change_id`: String
    public let `craft_id`: String
    public let `extension_id`: String
    public let `state`: ExtensionChangeState
}

public enum ExtensionChangeState: String {
    case `staged` = "staged"
    case `applied` = "applied"
    case `refused` = "refused"
    case `outcome_unknown` = "outcome_unknown"
}

public struct ExtensionConfirmation {
    public let `action`: ExtensionAction
    public let `catalog`: ExtensionCatalog
    public let `extension_id`: String
    public let `scope`: ExtensionScope
    public let `trust`: ExtensionTrust
}

public enum ExtensionScope: String {
    case `user` = "user"
}

public enum ExtensionTrust: String {
    case `same_user_executable` = "same_user_executable"
}

public struct ExternalConversation {
    public let `harness`: String
    public let `import_id`: String?
    public let `native_conversation`: String
    public let `origin`: ExternalOrigin
    public let `process`: ExternalProcess
}

public struct ExternalConversationList {
    public let `cursor`: String
    public let `discovered`: [ExternalConversation]
    public let `imported`: [ImportedConversation]
}

public enum ExternalOrigin {
    case `project`(ExternalOriginProject)
    case `unregistered`(ExternalOriginUnregistered)
    case `unknown`(ExternalOriginUnknown)
}

public enum ExternalProcess {
    case `none`(ExternalProcessNone)
    case `external`(ExternalProcessExternal)
    case `cooperating`(ExternalProcessCooperating)
}

public enum ExternalTool: String {
    case `git` = "git"
    case `git-lfs` = "git-lfs"
    case `ssh` = "ssh"
    case `tailscale` = "tailscale"
}

public struct ExternalToolStatus {
    public let `availability`: ToolAvailability
    public let `tool`: ExternalTool
}

public struct FileRevision {
    public let `mode`: String
    public let `object`: String
}

public enum FileTarget {
    case `project`(FileTargetProject)
    case `workspace`(FileTargetWorkspace)
}

public struct GitCheckpoint {
    public let `run_id`: String
    public let `turn`: UInt32
}

public struct GitDelivery {
    public let `acknowledged_by`: String?
    public let `checkpoint`: GitCheckpoint?
    public let `conversation_id`: String
    public let `delivery_id`: String
    public let `message`: GitMessage?
    public let `operation`: GitOperation
    public let `outcome`: GitDeliveryOutcome
    public let `policy`: GitDeliveryPolicy
    public let `utility_job`: String?
}

public enum GitDeliveryOutcome {
    case `pending`(GitDeliveryOutcomePending)
    case `completed`(GitDeliveryOutcomeCompleted)
    case `failed`(GitDeliveryOutcomeFailed)
    case `outcome_unknown`(GitDeliveryOutcomeOutcomeUnknown)
}

public struct GitDeliveryPolicy {
    public let `automatic`: Bool
    public let `branch`: Bool
    public let `branch_prefix`: String
    public let `commit`: Bool
    public let `draft_pull_request`: Bool
    public let `push`: Bool
}

public struct GitLink {
    public let `commit`: String
    public let `path`: String
}

public struct GitMessage {
    public let `body`: String
    public let `fallback_reason`: String?
    public let `title`: String
}

public enum GitOperation {
    case `branch`(GitOperationBranch)
    case `commit`(GitOperationCommit)
    case `push`(GitOperationPush)
    case `draft_pull_request`(GitOperationDraftPullRequest)
}

public struct HandoffRequest {
    public let `craft`: String
    public let `files`: [String]
    public let `plan`: String
    public let `source_run_id`: String
    public let `summary`: String
}

public struct ImportedConversation {
    public let `harness`: String
    public let `import_id`: String
    public let `imported_at_unix_ms`: Int64
    public let `imported_by`: Actor
    public let `native_conversation`: String
    public let `resumed_as`: String?
    public let `working_directory`: String?
}

public struct InstalledCraft {
    public let `craft_id`: String
    public let `harnesses`: [String]
    public let `subagent_control`: SubagentControl?
    public let `version`: String
}

public struct ManagedProcess {
    public let `label`: String?
    public let `pid`: UInt32
    public let `role`: ManagedProcessRole
    public let `running`: Bool
}

public enum ManagedProcessRole: String {
    case `helper` = "helper"
    case `harness` = "harness"
}

public struct ModelConsumption {
    public let `estimated`: UInt64
    public let `interim`: UInt64
    public let `last_observed_at_unix_ms`: Int64
    public let `measurements`: UInt64
    public let `model`: String?
    public let `tokens`: UsageTokens
}

public struct Name {
    public let `source`: NameSource
    public let `value`: String
}

public enum NameSource: String {
    case `manual` = "manual"
    case `utility` = "utility"
    case `harness_native` = "harness_native"
    case `deterministic` = "deterministic"
}

public struct NoVisaDestination {
    public let `plane_id`: String
    public let `ssh_endpoint`: String
    public let `workspace_id`: String
}

public struct NoVisaOrigin {
    public let `conversation_id`: String
    public let `plane_id`: String
    public let `run_id`: String
}

public struct NoVisaSelection {
    public let `account_binding_id`: String
    public let `conversation_id`: String
    public let `destinations`: [NoVisaDestination]
    public let `jet_equivalent`: [String]
    public let `native_unavailable`: [String]
    public let `origin_plane_id`: String
}

public struct ObservedConsumption {
    public let `estimated`: UInt64
    public let `interim`: UInt64
    public let `last_observed_at_unix_ms`: Int64?
    public let `measurements`: UInt64
    public let `models`: [ModelConsumption]
    public let `tokens`: UsageTokens
}

public struct OrphanedExecution {
    public let `execution_id`: String
    public let `metadata`: ExecutionMetadata?
    public let `role`: ExecutionRole?
}

public struct OrphanedExecutions {
    public let `executions`: [OrphanedExecution]
    public let `next`: String?
}

public typealias PageCursor = String

public struct PairedClient {
    public let `access`: PairedClientAccess
    public let `client_id`: String
    public let `key`: ClientPublicKey
    public let `paired_at_unix_ms`: Int64
    public let `pairing_protocol`: String
}

public enum PairedClientAccess: String {
    case `enabled` = "enabled"
    case `disabled` = "disabled"
}

public enum PairingDisclosure {
    case `manual_code`(PairingDisclosureManualCode)
    case `qr_payload`(PairingDisclosureQrPayload)
    case `already_disclosed`(PairingDisclosureAlreadyDisclosed)
}

public enum PairingEnd: String {
    case `expired` = "expired"
    case `too_many_attempts` = "too_many_attempts"
    case `gate_closed` = "gate_closed"
}

public enum PairingGate: String {
    case `open` = "open"
    case `closed` = "closed"
}

public enum PairingKeyAlgorithm: String {
    case `ed25519` = "ed25519"
}

public enum PairingMethod {
    case `manual_code`(PairingMethodManualCode)
    case `qr_payload`(PairingMethodQrPayload)
}

public enum PairingProgress {
    case `offered`(PairingProgressOffered)
    case `awaiting_confirmation`(PairingProgressAwaitingConfirmation)
    case `confirmed`(PairingProgressConfirmed)
    case `ended`(PairingProgressEnded)
}

public struct PairingSnapshot {
    public let `clients`: [PairedClient]?
    public let `cursor`: String
    public let `gate`: PairingGate
    public let `pending`: PendingPairing?
}

public struct PendingPairing {
    public let `attempts_remaining`: UInt32
    public let `expires_at_unix_ms`: Int64
    public let `method`: PairingMethod
    public let `offer_id`: String
    public let `opened_at_unix_ms`: Int64
    public let `progress`: PairingProgress
}

public struct PlaneStatus {
    public let `core_version`: String
    public let `cursor`: String?
    public let `daemon_starts`: UInt64
    public let `plane_id`: String
    public let `security`: SecurityState?
    public let `started_at_unix_ms`: Int64
}

public struct PlaneUsage {
    public let `consumption`: ObservedConsumption
    public let `cursor`: String
    public let `plane_id`: String
    public let `quota_windows`: [QuotaWindow]
}

public struct Platform {
    public let `architecture`: String
    public let `operating_system`: String
}

public enum PowerState: String {
    case `normal` = "normal"
    case `constrained` = "constrained"
    case `unavailable` = "unavailable"
}

public struct Project {
    public let `project_id`: String
    public let `registered_at_unix_ms`: Int64
    public let `registered_by`: Actor
    public let `root`: String
}

public struct ProjectEntry {
    public let `cursor`: String
    public let `kind`: EntryKind
    public let `path`: String
    public let `project_id`: String
}

public struct ProjectList {
    public let `cursor`: String
    public let `projects`: [Project]
}

public struct ProjectPreview {
    public let `registrability`: Registrability
    public let `root`: String
}

public struct PromotedChange {
    public let `kind`: ChangeKind
    public let `path`: String
}

public struct PromotionBinding {
    public let `actor`: String
    public let `base_commit`: String
    public let `conflicts`: [PromotionConflict]
    public let `destination`: PromotionDestination
    public let `destination_commit`: String
    public let `destination_dirty`: Bool
    public let `destination_tree`: String
    public let `result_tree`: String
    public let `workspace_id`: String
    public let `workspace_tree`: String
}

public struct PromotionConflict {
    public let `kind`: ConflictKind
    public let `path`: String
}

public enum PromotionDestination {
    case `local_checkout`(PromotionDestinationLocalCheckout)
    case `branch`(PromotionDestinationBranch)
}

public struct PromotionPreview {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `changes`: [PromotedChange]
    public let `cursor`: String
}

public enum PromotionState: String {
    case `applying` = "applying"
    case `promoted` = "promoted"
    case `conflicted` = "conflicted"
    case `failed` = "failed"
    case `outcome_unknown` = "outcome_unknown"
}

public enum QueryRequest {
    case `git_deliveries`(QueryRequestGitDeliveries)
    case `auto_continue`(QueryRequestAutoContinue)
    case `inspect_extension`(QueryRequestInspectExtension)
    case `extension_catalog`(QueryRequestExtensionCatalog)
    case `extension_change`(QueryRequestExtensionChange)
    case `remote_tool_review`(QueryRequestRemoteToolReview)
    case `utility`(QueryRequestUtility)
    case `discover_craft`(QueryRequestDiscoverCraft)
    case `scheduled_tasks`(QueryRequestScheduledTasks)
    case `editable_file`(QueryRequestEditableFile)
    case `workspace_terminals`(QueryRequestWorkspaceTerminals)
    case `change_artifact`(QueryRequestChangeArtifact)
    case `change_diff`(QueryRequestChangeDiff)
    case `next_change_diff`(QueryRequestNextChangeDiff)
    case `turn_queue`(QueryRequestTurnQueue)
    case `orphaned_executions`(QueryRequestOrphanedExecutions)
    case `run_execution`(QueryRequestRunExecution)
    case `status`(QueryRequestStatus)
    case `conversations`(QueryRequestConversations)
    case `next_conversations`(QueryRequestNextConversations)
    case `conversation`(QueryRequestConversation)
    case `capabilities`(QueryRequestCapabilities)
    case `account_bindings`(QueryRequestAccountBindings)
    case `usage`(QueryRequestUsage)
    case `settings`(QueryRequestSettings)
    case `events`(QueryRequestEvents)
    case `pairing`(QueryRequestPairing)
    case `security_audit`(QueryRequestSecurityAudit)
    case `projects`(QueryRequestProjects)
    case `preview_project`(QueryRequestPreviewProject)
    case `project_entry`(QueryRequestProjectEntry)
    case `preview_promotion`(QueryRequestPreviewPromotion)
    case `search`(QueryRequestSearch)
    case `external_conversations`(QueryRequestExternalConversations)
}

public enum QueryResponse {
    case `git_deliveries`(QueryResponseGitDeliveries)
    case `auto_continue`(QueryResponseAutoContinue)
    case `extension_catalog`(QueryResponseExtensionCatalog)
    case `extension_change`(QueryResponseExtensionChange)
    case `remote_tool_review`(QueryResponseRemoteToolReview)
    case `utility`(QueryResponseUtility)
    case `craft_installation_preview`(QueryResponseCraftInstallationPreview)
    case `scheduled_tasks`(QueryResponseScheduledTasks)
    case `editable_file`(QueryResponseEditableFile)
    case `workspace_terminals`(QueryResponseWorkspaceTerminals)
    case `change_artifact`(QueryResponseChangeArtifact)
    case `change_diff`(QueryResponseChangeDiff)
    case `turn_queue`(QueryResponseTurnQueue)
    case `orphaned_executions`(QueryResponseOrphanedExecutions)
    case `run_execution`(QueryResponseRunExecution)
    case `status`(QueryResponseStatus)
    case `conversations`(QueryResponseConversations)
    case `conversation`(QueryResponseConversation)
    case `capabilities`(QueryResponseCapabilities)
    case `account_bindings`(QueryResponseAccountBindings)
    case `usage`(QueryResponseUsage)
    case `settings`(QueryResponseSettings)
    case `events`(QueryResponseEvents)
    case `pairing`(QueryResponsePairing)
    case `security_audit`(QueryResponseSecurityAudit)
    case `projects`(QueryResponseProjects)
    case `project_preview`(QueryResponseProjectPreview)
    case `project_entry`(QueryResponseProjectEntry)
    case `promotion_preview`(QueryResponsePromotionPreview)
    case `search`(QueryResponseSearch)
    case `external_conversations`(QueryResponseExternalConversations)
}

public struct QuotaMeasure {
    public let `limit`: UInt64?
    public let `unit`: QuotaUnit
    public let `used`: UInt64
}

public enum QuotaScope {
    case `provider_account`(QuotaScopeProviderAccount)
    case `model`(QuotaScopeModel)
}

public enum QuotaUnit: String {
    case `tokens` = "tokens"
    case `requests` = "requests"
    case `credits` = "credits"
    case `share` = "share"
}

public struct QuotaWindow {
    public let `binding_id`: String
    public let `conversation_id`: String?
    public let `estimation`: UsageEstimation
    public let `finality`: UsageFinality
    public let `freshness`: UsageFreshness
    public let `measure`: QuotaMeasure
    public let `observed_at_unix_ms`: Int64
    public let `provider`: String
    public let `resets_at_unix_ms`: Int64?
    public let `run_id`: String?
    public let `scope`: QuotaScope
    public let `window`: String
    public let `window_seconds`: UInt64?
}

public enum RecoveryAction {
    case `refresh_file`(RecoveryActionRefreshFile)
    case `refresh_conversation`(RecoveryActionRefreshConversation)
    case `refresh_run`(RecoveryActionRefreshRun)
    case `resume_events`(RecoveryActionResumeEvents)
}

public enum Registrability {
    case `registrable`(RegistrabilityRegistrable)
    case `not_a_repository`(RegistrabilityNotARepository)
    case `broken_repository`(RegistrabilityBrokenRepository)
    case `bare_repository`(RegistrabilityBareRepository)
    case `inside_git_dir`(RegistrabilityInsideGitDir)
    case `inside_working_tree`(RegistrabilityInsideWorkingTree)
}

public struct RemoteEnvironment {
    public let `name`: String
    public let `value`: String?
}

public enum RemoteGitOperation: String {
    case `status` = "status"
    case `diff` = "diff"
}

public enum RemotePairingRequest {
    case `claim`(RemotePairingRequestClaim)
    case `complete`(RemotePairingRequestComplete)
}

public enum RemotePairingResponse {
    case `claimed`(RemotePairingResponseClaimed)
    case `completed`(RemotePairingResponseCompleted)
    case `rejected`(RemotePairingResponseRejected)
}

public enum RemoteToolAction {
    case `terminal`(RemoteToolActionTerminal)
    case `process`(RemoteToolActionProcess)
    case `git`(RemoteToolActionGit)
    case `shell`(RemoteToolActionShell)
    case `write_file`(RemoteToolActionWriteFile)
    case `read_file`(RemoteToolActionReadFile)
}

public enum RemoteToolDecision: String {
    case `allow_once` = "allow_once"
    case `deny` = "deny"
}

public struct RemoteToolRequest {
    public let `action`: RemoteToolAction
    public let `destination_plane_id`: String
    public let `operation_id`: String
    public let `origin`: NoVisaOrigin
    public let `permissions`: [BrokerPermission]
    public let `workspace_id`: String
}

public enum RemoteToolResult {
    case `approval_required`(RemoteToolResultApprovalRequired)
    case `process`(RemoteToolResultProcess)
    case `written`(RemoteToolResultWritten)
    case `file`(RemoteToolResultFile)
}

public struct Repository {
    public let `checkout`: Checkout
    public let `lfs`: ToolAvailability
    public let `submodules`: [GitLink]
    public let `worktree`: Worktree
}

public struct ResolvedSetting {
    public let `key`: SettingKey
    public let `source`: SettingSource
    public let `value`: SettingValue
}

public struct ResourceBudgets {
    public let `craft_rss_mib`: UInt32
    public let `helper_rss_mib`: UInt32
    public let `idle_cpu_millicores`: UInt32
    public let `idle_window_seconds`: UInt32
    public let `jetd_rss_mib`: UInt32
    public let `power`: PowerState
}

public enum RestartMetadata {
    case `cursor_expired`(RestartMetadataCursorExpired)
    case `cursor_ahead`(RestartMetadataCursorAhead)
    case `pagination_stale`(RestartMetadataPaginationStale)
}

public enum RetentionPolicy: String {
    case `retain` = "retain"
    case `forget_after_final_run` = "forget_after_final_run"
}

public struct ReviewComment {
    public let `comment`: String
    public let `line`: UInt32
    public let `path`: String
}

public struct RevisionConflict {
    public let `current_revision`: String
    public let `safe_state`: ConflictState
}

public struct Run {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public enum RunActivity: String {
    case `working` = "working"
    case `waiting_for_user` = "waiting_for_user"
    case `waiting_for_approval` = "waiting_for_approval"
    case `waiting_for_auth` = "waiting_for_auth"
    case `waiting_for_quota` = "waiting_for_quota"
    case `reconnecting` = "reconnecting"
}

public enum RunControl: String {
    case `interrupt_turn` = "interrupt_turn"
    case `stop_run` = "stop_run"
}

public struct RunExecution {
    public let `activity`: RunActivity?
    public let `cursor`: String
    public let `exit_code`: Int32?
    public let `native_conversation`: String?
    public let `needs_attention`: Bool?
    public let `no_visa`: NoVisaSelection?
    public let `processes`: [ManagedProcess]
    public let `run`: Run
    public let `termination`: RunTermination?
    public let `visa`: VisaSelection?
}

public enum RunLifecycle: String {
    case `created` = "created"
    case `starting` = "starting"
    case `active` = "active"
    case `stopping` = "stopping"
    case `completed` = "completed"
    case `failed` = "failed"
    case `canceled` = "canceled"
    case `lost` = "lost"
}

public struct RunTermination {
    public let `control`: RunControl
    public let `stage`: TerminationStage
}

public struct ScheduleFiring {
    public let `due_at_unix_ms`: Int64
    public let `firing_id`: String
    public let `intended_local`: String
}

public struct ScheduledTask {
    public let `authorized_by`: String
    public let `conversation_id`: String
    public let `local_time`: String
    public let `next`: ScheduleFiring
    public let `prompt`: String
    public let `schedule_id`: String
    public let `time_zone`: String
}

public struct ScheduledTasks {
    public let `cursor`: String
    public let `tasks`: [ScheduledTask]
}

public enum SearchField: String {
    case `name` = "name"
    case `path` = "path"
    case `branch` = "branch"
}

public struct SearchHit {
    public let `conversation_id`: String
    public let `excerpt`: String
    public let `field`: SearchField
    public let `sequence`: String
}

public struct SearchResult {
    public let `cursor`: String
    public let `hits`: [SearchHit]
    public let `indexed_through`: String
}

public struct SecurityAudit {
    public let `cursor`: String
    public let `entries`: [AuditEntry]
}

public enum SecurityState {
    case `trusted`(SecurityStateTrusted)
    case `degraded`(SecurityStateDegraded)
}

public enum SeedSelection {
    case `none`(SeedSelectionNone)
    case `all_eligible`(SeedSelectionAllEligible)
    case `paths`(SeedSelectionPaths)
}

public enum ServerHello {
    case `challenge`(ServerHelloChallenge)
    case `welcome`(ServerHelloWelcome)
    case `rejected`(ServerHelloRejected)
}

public enum ServerMessage {
    case `remote_tool_result`(ServerMessageRemoteToolResult)
    case `terminal_attached`(ServerMessageTerminalAttached)
    case `terminal_resized`(ServerMessageTerminalResized)
    case `query_result`(ServerMessageQueryResult)
    case `command_result`(ServerMessageCommandResult)
    case `error`(ServerMessageError)
}

public enum SettingKey: String {
    case `storage.disposable_mib` = "storage.disposable_mib"
    case `energy.concurrency` = "energy.concurrency"
    case `energy.low_power_concurrency` = "energy.low_power_concurrency"
    case `energy.constrained` = "energy.constrained"
    case `energy.foreground_override` = "energy.foreground_override"
    case `artifact.max_mib` = "artifact.max_mib"
    case `artifact.run_mib` = "artifact.run_mib"
    case `utility.account_binding` = "utility.account_binding"
    case `utility.content_consent` = "utility.content_consent"
    case `utility.autodelete_compilation` = "utility.autodelete_compilation"
    case `utility.git_text` = "utility.git_text"
    case `utility.automatic_naming` = "utility.automatic_naming"
    case `git.auto_commit` = "git.auto_commit"
    case `git.auto_branch` = "git.auto_branch"
    case `git.auto_push` = "git.auto_push"
    case `git.auto_draft_pull_request` = "git.auto_draft_pull_request"
    case `git.branch_prefix` = "git.branch_prefix"
    case `git.message_instructions` = "git.message_instructions"
    case `security.audit_retention_days` = "security.audit_retention_days"
    case `craft.developer_mode` = "craft.developer_mode"
    case `review.automatic` = "review.automatic"
    case `review.account_binding` = "review.account_binding"
    case `review.cross_provider_consent` = "review.cross_provider_consent"
}

public enum SettingScope {
    case `plane`(SettingScopePlane)
    case `project`(SettingScopeProject)
    case `conversation`(SettingScopeConversation)
}

public enum SettingSelection {
    case `all`(SettingSelectionAll)
    case `key`(SettingSelectionKey)
}

public struct SettingSnapshot {
    public let `cursor`: String
    public let `scope`: SettingScope
    public let `settings`: [ResolvedSetting]
}

public enum SettingSource {
    case `built_in`(SettingSourceBuiltIn)
    case `scope`(SettingSourceScope)
}

public enum SettingValue {
    case `flag`(SettingValueFlag)
    case `text`(SettingValueText)
    case `count`(SettingValueCount)
}

public typealias Sha256Digest = String

public enum StreamControl {
    case `credit`(StreamControlCredit)
    case `terminal_gap`(StreamControlTerminalGap)
    case `terminal_finished`(StreamControlTerminalFinished)
    case `artifact_finished`(StreamControlArtifactFinished)
}

public enum SubagentControl: String {
    case `monitor_only` = "monitor_only"
    case `native_limits` = "native_limits"
}

public enum TerminalState: String {
    case `opening` = "opening"
    case `open` = "open"
    case `closing` = "closing"
    case `closed` = "closed"
    case `unavailable` = "unavailable"
}

public enum TerminationStage: String {
    case `native_cancellation` = "native_cancellation"
    case `interrupt` = "interrupt"
    case `terminate` = "terminate"
    case `kill` = "kill"
    case `unobserved` = "unobserved"
}

public enum ToolAvailability {
    case `present`(ToolAvailabilityPresent)
    case `missing`(ToolAvailabilityMissing)
}

public struct Turn {
    public let `client_id`: String
    public let `run_id`: String?
    public let `sequence`: String
    public let `source`: TurnSource
    public let `state`: TurnState
    public let `turn_id`: String
}

public enum TurnOutcome: String {
    case `completed` = "completed"
    case `interrupted` = "interrupted"
}

public struct TurnQueue {
    public let `cursor`: String
    public let `turns`: [Turn]
}

public enum TurnSource: String {
    case `user` = "user"
    case `schedule` = "schedule"
    case `auto_continue` = "auto_continue"
}

public enum TurnState: String {
    case `queued` = "queued"
    case `active` = "active"
    case `completed` = "completed"
    case `superseded` = "superseded"
    case `canceled` = "canceled"
    case `withdrawn` = "withdrawn"
    case `failed` = "failed"
    case `outcome_unknown` = "outcome_unknown"
}

public enum UsageEstimation: String {
    case `measured` = "measured"
    case `estimated` = "estimated"
}

public enum UsageFinality: String {
    case `interim` = "interim"
    case `final` = "final"
}

public enum UsageFreshness {
    case `fresh`(UsageFreshnessFresh)
    case `stale`(UsageFreshnessStale)
    case `unreachable`(UsageFreshnessUnreachable)
}

public enum UsageSelection {
    case `plane`(UsageSelectionPlane)
    case `binding`(UsageSelectionBinding)
    case `conversation`(UsageSelectionConversation)
    case `run`(UsageSelectionRun)
}

public struct UsageTokens {
    public let `cached_input`: UInt64
    public let `input`: UInt64
    public let `output`: UInt64
    public let `reasoning`: UInt64
}

public struct UtilityJob {
    public let `binding_id`: String?
    public let `job_id`: String
    public let `model`: String?
    public let `outcome`: UtilityOutcome
    public let `plane_id`: String
    public let `policy`: UtilityPolicy
    public let `provider`: String?
    public let `purpose`: UtilityPurpose
}

public enum UtilityOutcome {
    case `pending`(UtilityOutcomePending)
    case `draft`(UtilityOutcomeDraft)
    case `text`(UtilityOutcomeText)
    case `refused`(UtilityOutcomeRefused)
}

public struct UtilityPolicy {
    public let `cross_provider_consent`: Bool
    public let `enabled`: Bool
    public let `version`: UInt32
}

public enum UtilityPurpose: String {
    case `naming` = "naming"
    case `git_text` = "git_text"
    case `autodelete` = "autodelete"
}

public enum UtilityRequest {
    case `naming`(UtilityRequestNaming)
    case `git_text`(UtilityRequestGitText)
    case `autodelete`(UtilityRequestAutodelete)
}

public struct VersionRange {
    public let `max`: UInt32
    public let `min`: UInt32
}

public struct VisaSelection {
    public let `account_binding_id`: String
    public let `plane_id`: String
}

public struct WireError {
    public let `category`: ErrorCategory
    public let `code`: String
    public let `message`: String
    public let `recovery_actions`: [RecoveryAction]?
    public let `restart`: RestartMetadata?
    public let `retryable`: Bool
    public let `revision_conflict`: RevisionConflict?
}

public enum WorkingTree {
    case `no_project`(WorkingTreeNoProject)
    case `workspace`(WorkingTreeWorkspace)
    case `local_checkout`(WorkingTreeLocalCheckout)
}

public enum WorkingTreeRequest {
    case `no_project`(WorkingTreeRequestNoProject)
    case `workspace`(WorkingTreeRequestWorkspace)
    case `local_checkout`(WorkingTreeRequestLocalCheckout)
}

public struct Workspace {
    public let `base`: WorkspaceBase
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `project_id`: String
    public let `promotion`: WorkspacePromotion?
    public let `root`: String
    public let `seed`: WorkspaceSeed?
    public let `workspace_id`: String
}

public struct WorkspaceBase {
    public let `commit`: String
    public let `selection`: BaseSelection
}

public struct WorkspacePromotion {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `promotion_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `settled_at_unix_ms`: Int64?
    public let `state`: PromotionState
}

public struct WorkspaceSeed {
    public let `changed_paths`: UInt32
    public let `tree`: String
}

public struct WorkspaceTerminal {
    public let `state`: TerminalState
    public let `terminal_id`: String
    public let `workspace_id`: String
}

public enum Worktree {
    case `main`(WorktreeMain)
    case `linked`(WorktreeLinked)
}

public struct ActorInteractiveClient {
    public let `client_id`: String
}

public struct ArtifactControlArtifactUpload {
    public let `artifact`: ArtifactDescriptor
    public let `run_id`: String
}

public struct ArtifactControlArtifactCommit {

}

public struct ArtifactControlArtifactPublished {
    public let `artifact`: ArtifactDescriptor
}

public struct ArtifactControlArtifactDownload {
    public let `sha256`: Sha256Digest
}

public struct ArtifactControlArtifactDownloading {
    public let `artifact`: ArtifactDescriptor
}

public struct ArtifactControlArtifactCancel {

}

public struct ArtifactControlArtifactCanceled {

}

public struct ArtifactControlArtifactCollect {

}

public struct ArtifactControlArtifactCollected {
    public let `removed`: UInt32
}

public struct AuditActorInteractiveClient {
    public let `client_id`: String
}

public struct AuditActorCraftRevocation {

}

public struct AuditBreachHeadMissing {

}

public struct AuditBreachHeadNotInStore {

}

public struct AuditBreachHeadDiverged {

}

public struct AuditBreachRecordAltered {
    public let `sequence`: String
}

public struct AuditBreachTargetAltered {
    public let `sequence`: String
}

public struct AutoContinuePolicyOff {

}

public struct AutoContinuePolicyRetry {
    public let `delay_ms`: UInt32
    public let `max_delay_ms`: UInt32
    public let `max_retries`: UInt32
    public let `message`: String
}

public struct AutoContinueTargetVariant0 {
    public let `account_binding`: String
}

public struct AutoContinueTargetVariant1 {
    public let `conversation`: String
}

public struct BaseSelectionHead {

}

public struct BaseSelectionRevision {
    public let `revision`: String
}

public struct CapabilityObservationLastObserved {

}

public struct CapabilityObservationFresh {

}

public struct ChangeOriginUserEdit {
    public let `client_id`: String
}

public struct ChangeOriginWorkspaceTerminal {
    public let `terminal_id`: String
}

public struct ChangeOriginHarness {
    public let `run_id`: String
}

public struct ChangeOriginMixed {

}

public struct ChangeOriginExternalOrUnknown {

}

public struct ClientMessageRemoteTool {
    public let `id`: UInt64
    public let `request`: RemoteToolRequest
}

public struct ClientMessageAttachTerminal {
    public let `after`: String
    public let `credit`: String
    public let `id`: UInt64
    public let `terminal_id`: String
}

public struct ClientMessageResizeTerminal {
    public let `columns`: Int64
    public let `id`: UInt64
    public let `rows`: Int64
}

public struct ClientMessageQuery {
    public let `id`: UInt64
    public let `query`: QueryRequest
    public let `timeout_ms`: UInt32?
}

public struct ClientMessageCommand {
    public let `command`: CommandRequest
    public let `command_id`: String
    public let `id`: UInt64
}

public struct CommandRequestAcknowledgeGitDelivery {
    public let `delivery_id`: String
}

public struct CommandRequestDeliverGit {
    public let `checkpoint`: GitCheckpoint?
    public let `conversation_id`: String
    public let `operation`: GitOperation
}

public struct CommandRequestSetAutoContinue {
    public let `policy`: AutoContinuePolicy
    public let `target`: AutoContinueTarget
}

public struct CommandRequestAuthorizeApprovalRetry {
    public let `review_id`: String
    public let `run_id`: String
}

public struct CommandRequestChangeExtension {
    public let `confirmation`: ExtensionConfirmation
}

public struct CommandRequestReviewRemoteTool {
    public let `client_id`: String
    public let `decision`: RemoteToolDecision
    public let `operation_id`: String
}

public struct CommandRequestRequestUtility {
    public let `request`: UtilityRequest
}

public struct CommandRequestDisableCraft {
    public let `craft_id`: String
    public let `mode`: CraftDisableMode
}

public struct CommandRequestInstallCraft {
    public let `confirmation`: CraftInstallationConfirmation
}

public struct CommandRequestCreateSchedule {
    public let `conversation_id`: String
    public let `local_time`: String
    public let `prompt`: String
    public let `time_zone`: String
}

public struct CommandRequestCancelSchedule {
    public let `schedule_id`: String
}

public struct CommandRequestApplyUserEdit {
    public let `content`: String
    public let `expected_revision`: FileRevision
    public let `path`: String
    public let `target`: FileTarget
}

public struct CommandRequestSubmitReview {
    public let `comments`: [ReviewComment]
    public let `conversation_id`: String
}

public struct CommandRequestSetConversationName {
    public let `conversation_id`: String
    public let `expected_revision`: String
    public let `name`: String
}

public struct CommandRequestSetRunName {
    public let `expected_revision`: String
    public let `name`: String
    public let `run_id`: String
}

public struct CommandRequestOpenTerminal {
    public let `columns`: Int64
    public let `rows`: Int64
    public let `workspace_id`: String
}

public struct CommandRequestCloseTerminal {
    public let `terminal_id`: String
}

public struct CommandRequestWithdrawTurn {
    public let `conversation_id`: String
    public let `turn_id`: String
}

public struct CommandRequestSubmitTurn {
    public let `conversation_id`: String
    public let `prompt`: String
    public let `source`: TurnSource?
}

public struct CommandRequestResolveExecution {
    public let `action`: ExecutionAction
    public let `execution_id`: String
    public let `instance`: String?
}

public struct CommandRequestInterruptTurn {
    public let `run_id`: String
}

public struct CommandRequestStopRun {
    public let `run_id`: String
}

public struct CommandRequestStartVisaRun {
    public let `account_binding_id`: String
    public let `conversation_id`: String
    public let `craft`: String
    public let `destination_plane_id`: String
    public let `prompt`: String
}

public struct CommandRequestStartNoVisaRun {
    public let `account_binding_id`: String
    public let `conversation_id`: String
    public let `craft`: String
    public let `destinations`: [NoVisaDestination]
    public let `origin_plane_id`: String
    public let `prompt`: String
}

public struct CommandRequestStartRun {
    public let `conversation_id`: String
    public let `craft`: String
    public let `prompt`: String
}

public struct CommandRequestCreateConversation {
    public let `retention`: RetentionPolicy?
    public let `working_tree`: WorkingTreeRequest?
}

public struct CommandRequestHandoffConversation {
    public let `craft`: String
    public let `files`: [String]
    public let `plan`: String
    public let `source_run_id`: String
    public let `summary`: String
}

public struct CommandRequestForkConversation {
    public let `checkpoint_turn`: UInt32
    public let `source_run_id`: String
}

public struct CommandRequestCreateRun {
    public let `conversation_id`: String
}

public struct CommandRequestSetSetting {
    public let `key`: SettingKey
    public let `scope`: SettingScope
    public let `value`: SettingValue
}

public struct CommandRequestClearSetting {
    public let `key`: SettingKey
    public let `scope`: SettingScope
}

public struct CommandRequestBindAccount {
    public let `credential_source`: CredentialSource
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct CommandRequestUnbindAccount {
    public let `binding_id`: String
}

public struct CommandRequestBeginAuditEpoch {

}

public struct CommandRequestSetPairingGate {
    public let `gate`: PairingGate
}

public struct CommandRequestOpenPairing {
    public let `method`: PairingMethod
}

public struct CommandRequestClaimPairing {
    public let `key`: ClientPublicKey
    public let `secret`: String
}

public struct CommandRequestConfirmPairing {
    public let `authentication_string`: String
    public let `offer_id`: String
}

public struct CommandRequestCompletePairing {
    public let `offer_id`: String
    public let `signature`: String
}

public struct CommandRequestSetPairedClientAccess {
    public let `access`: PairedClientAccess
    public let `client_id`: String
}

public struct CommandRequestRevokePairedClient {
    public let `client_id`: String
}

public struct CommandRequestTransitionRun {
    public let `expected_revision`: String
    public let `lifecycle`: RunLifecycle
    public let `run_id`: String
}

public struct CommandRequestRegisterProject {
    public let `path`: String
}

public struct CommandRequestPromoteWorkspace {
    public let `binding`: PromotionBinding
}

public struct CommandRequestImportConversation {
    public let `harness`: String
    public let `native_conversation`: String
}

public struct CommandRequestResumeImportedConversation {
    public let `import_id`: String
    public let `retention`: RetentionPolicy?
    public let `working_tree`: WorkingTreeRequest
}

public struct CommandResponseGitDeliveryAcknowledged {
    public let `delivery_id`: String
}

public struct CommandResponseGitDeliveryQueued {
    public let `delivery_id`: String
}

public struct CommandResponseAutoContinueConfigured {

}

public struct CommandResponseApprovalRetryAuthorized {
    public let `review_id`: String
}

public struct CommandResponseExtensionChangeQueued {
    public let `change_id`: String
}

public struct CommandResponseRemoteToolReviewed {
    public let `operation_id`: String
}

public struct CommandResponseUtilityQueued {
    public let `job_id`: String
}

public struct CommandResponseCraftDisabled {
    public let `craft_id`: String
    public let `mode`: CraftDisableMode
}

public struct CommandResponseCraftInstallationQueued {
    public let `artifact_sha256`: String
    public let `craft_id`: String
    public let `version`: String
}

public struct CommandResponseScheduleCreated {
    public let `task`: ScheduledTask
}

public struct CommandResponseScheduleCanceled {
    public let `schedule_id`: String
}

public struct CommandResponseUserEditApplied {
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public struct CommandResponseConversationNamed {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct CommandResponseRunNamed {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseTerminal {
    public let `terminal`: WorkspaceTerminal
}

public struct CommandResponseTurnWithdrawn {
    public let `turn`: Turn
}

public struct CommandResponseTurnAdmitted {
    public let `turn`: Turn
}

public struct CommandResponseRunControlAccepted {
    public let `control`: RunControl
    public let `run`: Run
}

public struct CommandResponseExecutionResolutionRecorded {
    public let `action`: ExecutionAction
    public let `execution_id`: String
}

public struct CommandResponseConversationCreated {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `name`: Name?
    public let `origin`: ConversationOrigin?
    public let `retention`: RetentionPolicy
    public let `revision`: String?
    public let `working_tree`: WorkingTree?
}

public struct CommandResponseRunCreated {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseRunTransitioned {
    public let `conversation_id`: String
    public let `created_at_unix_ms`: Int64
    public let `ended_at_unix_ms`: Int64?
    public let `lifecycle`: RunLifecycle
    public let `name`: Name?
    public let `revision`: String
    public let `run_id`: String
}

public struct CommandResponseSettingSet {
    public let `key`: SettingKey
    public let `scope`: SettingScope
    public let `value`: SettingValue
}

public struct CommandResponseSettingCleared {
    public let `key`: SettingKey
    public let `scope`: SettingScope
}

public struct CommandResponseAccountBound {
    public let `binding_id`: String
    public let `created_at_unix_ms`: Int64
    public let `credential_reference`: CredentialReference
    public let `label`: String
    public let `provider`: String
    public let `provider_account`: String?
}

public struct CommandResponseAccountUnbound {
    public let `binding_id`: String
    public let `credential_reference`: CredentialReference
}

public struct CommandResponsePairingGateSet {
    public let `gate`: PairingGate
}

public struct CommandResponsePairingOpened {
    public let `disclosure`: PairingDisclosure
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingClaimed {
    public let `challenge`: String
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingConfirmed {
    public let `pending`: PendingPairing
}

public struct CommandResponsePairingCompleted {
    public let `client`: PairedClient
}

public struct CommandResponsePairedClientAccessSet {
    public let `client`: PairedClient
}

public struct CommandResponsePairedClientRevoked {
    public let `client_id`: String
}

public struct CommandResponseAuditEpochBegun {
    public let `epoch`: String
}

public struct CommandResponseProjectRegistered {
    public let `project_id`: String
    public let `registered_at_unix_ms`: Int64
    public let `registered_by`: Actor
    public let `root`: String
}

public struct CommandResponseWorkspacePromotionRecorded {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `promotion_id`: String
    public let `recorded_at_unix_ms`: Int64
    public let `settled_at_unix_ms`: Int64?
    public let `state`: PromotionState
}

public struct CommandResponseConversationImported {
    public let `harness`: String
    public let `import_id`: String
    public let `imported_at_unix_ms`: Int64
    public let `imported_by`: Actor
    public let `native_conversation`: String
    public let `resumed_as`: String?
    public let `working_directory`: String?
}

public struct ConflictStateConversation {
    public let `conversation`: Conversation
}

public struct ConflictStateRun {
    public let `run`: Run
}

public struct ConversationOriginNew {

}

public struct ConversationOriginImported {
    public let `import_id`: String
}

public struct ConversationOriginForked {
    public let `checkpoint_turn`: UInt32
    public let `source_conversation_id`: String
    public let `source_run_id`: String
}

public struct CraftHostAccessExecutable {
    public let `name`: String
}

public struct CraftHostAccessFilesystem {
    public let `path`: String
}

public struct CraftHostAccessEnvironment {
    public let `name`: String
}

public struct CraftHostAccessNetwork {
    public let `destination`: String
}

public struct CraftSourceGithubRelease {
    public let `repository`: String
    public let `tag`: String
}

public struct CraftSourceLocal {
    public let `artifact`: String
    public let `specification`: String
}

public struct CredentialReferencePlatformStore {
    public let `item`: CredentialItem
}

public struct CredentialReferenceExternalHelper {
    public let `helper`: String
}

public struct CredentialReferenceHarnessNative {

}

public struct CredentialReferenceSessionOnly {
    public let `established_at_daemon_start`: UInt64
}

public struct CredentialSourcePlatformStore {

}

public struct CredentialSourceExternalHelper {
    public let `helper`: String
}

public struct CredentialSourceHarnessNative {

}

public struct CredentialSourceSessionOnly {

}

public struct CredentialStateResolvable {

}

public struct CredentialStateResolvedAtUse {

}

public struct CredentialStateWaitingForUnlock {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStateUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStateInvalidatedByRestart {

}

public struct CredentialStoreStatusAvailable {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStoreStatusLocked {
    public let `kind`: CredentialStoreKind
}

public struct CredentialStoreStatusUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct DegradedConditionMissingExternalTool {
    public let `tool`: ExternalTool
}

public struct DegradedConditionNoHarnessAvailable {

}

public struct DegradedConditionCredentialStoreUnavailable {
    public let `kind`: CredentialStoreKind
}

public struct DegradedConditionCredentialStoreLocked {
    public let `kind`: CredentialStoreKind
}

public struct DiffScopeCurrent {

}

public struct DiffScopeFinal {

}

public struct DiffScopeHistorical {
    public let `from_turn`: UInt32
    public let `to_turn`: UInt32
}

public struct DiffScopeTurn {
    public let `turn`: UInt32
}

public struct EntryKindFile {
    public let `bytes`: UInt64
}

public struct EntryKindDirectory {

}

public struct EntryKindOther {

}

public struct EntryKindMissing {

}

public struct EventOriginAutoContinue {

}

public struct EventOriginScheduledTask {
    public let `schedule_id`: String
}

public struct EventOriginHarness {
    public let `run_id`: String
}

public struct EventOriginRunSupervisor {
    public let `run_id`: String
}

public struct ExternalOriginProject {
    public let `project_id`: String
    public let `working_directory`: String
}

public struct ExternalOriginUnregistered {
    public let `working_directory`: String
}

public struct ExternalOriginUnknown {

}

public struct ExternalProcessNone {

}

public struct ExternalProcessExternal {
    public let `pid`: UInt32
}

public struct ExternalProcessCooperating {
    public let `endpoint`: String
    public let `pid`: UInt32
}

public struct FileTargetProject {
    public let `project_id`: String
}

public struct FileTargetWorkspace {
    public let `workspace_id`: String
}

public struct GitDeliveryOutcomePending {

}

public struct GitDeliveryOutcomeCompleted {
    public let `branch`: String?
    public let `head`: String
    public let `pull_request`: String?
}

public struct GitDeliveryOutcomeFailed {
    public let `code`: String
}

public struct GitDeliveryOutcomeOutcomeUnknown {

}

public struct GitOperationBranch {
    public let `name`: String
}

public struct GitOperationCommit {

}

public struct GitOperationPush {
    public let `remote`: String
}

public struct GitOperationDraftPullRequest {
    public let `base`: String?
    public let `remote`: String
}

public struct PairingDisclosureManualCode {
    public let `code`: String
}

public struct PairingDisclosureQrPayload {
    public let `payload`: String
}

public struct PairingDisclosureAlreadyDisclosed {

}

public struct PairingMethodManualCode {

}

public struct PairingMethodQrPayload {
    public let `endpoint`: String
}

public struct PairingProgressOffered {

}

public struct PairingProgressAwaitingConfirmation {
    public let `authentication_string`: String
    public let `client_id`: String
}

public struct PairingProgressConfirmed {
    public let `authentication_string`: String
    public let `client_id`: String
}

public struct PairingProgressEnded {
    public let `reason`: PairingEnd
}

public struct PromotionDestinationLocalCheckout {

}

public struct PromotionDestinationBranch {
    public let `name`: String
}

public struct QueryRequestGitDeliveries {
    public let `conversation_id`: String
}

public struct QueryRequestAutoContinue {
    public let `target`: AutoContinueTarget
}

public struct QueryRequestInspectExtension {
    public let `craft_id`: String
    public let `extension_id`: String
}

public struct QueryRequestExtensionCatalog {
    public let `craft_id`: String
}

public struct QueryRequestExtensionChange {
    public let `change_id`: String
}

public struct QueryRequestRemoteToolReview {
    public let `client_id`: String
    public let `operation_id`: String
}

public struct QueryRequestUtility {
    public let `job_id`: String
}

public struct QueryRequestDiscoverCraft {
    public let `source`: CraftSource
}

public struct QueryRequestScheduledTasks {
    public let `conversation_id`: String
}

public struct QueryRequestEditableFile {
    public let `path`: String
    public let `target`: FileTarget
}

public struct QueryRequestWorkspaceTerminals {
    public let `workspace_id`: String
}

public struct QueryRequestChangeArtifact {
    public let `offset`: String
    public let `sha256`: String
}

public struct QueryRequestChangeDiff {
    public let `run_id`: String
    public let `scope`: DiffScope
}

public struct QueryRequestNextChangeDiff {
    public let `cursor`: PageCursor
}

public struct QueryRequestTurnQueue {
    public let `conversation_id`: String
}

public struct QueryRequestOrphanedExecutions {
    public let `after`: String?
}

public struct QueryRequestRunExecution {
    public let `run_id`: String
}

public struct QueryRequestStatus {

}

public struct QueryRequestConversations {

}

public struct QueryRequestNextConversations {
    public let `cursor`: PageCursor
}

public struct QueryRequestConversation {
    public let `conversation_id`: String
}

public struct QueryRequestCapabilities {
    public let `observation`: CapabilityObservation
}

public struct QueryRequestAccountBindings {
    public let `observation`: CapabilityObservation
}

public struct QueryRequestUsage {
    public let `selection`: UsageSelection
}

public struct QueryRequestSettings {
    public let `scope`: SettingScope
    public let `selection`: SettingSelection
}

public struct QueryRequestEvents {
    public let `after`: String
}

public struct QueryRequestPairing {

}

public struct QueryRequestSecurityAudit {
    public let `after`: String
}

public struct QueryRequestProjects {

}

public struct QueryRequestPreviewProject {
    public let `observation`: CapabilityObservation
    public let `path`: String
}

public struct QueryRequestProjectEntry {
    public let `path`: String
    public let `project_id`: String
}

public struct QueryRequestPreviewPromotion {
    public let `destination`: PromotionDestination
    public let `workspace_id`: String
}

public struct QueryRequestSearch {
    public let `text`: String
}

public struct QueryRequestExternalConversations {

}

public struct QueryResponseGitDeliveries {
    public let `deliveries`: [GitDelivery]
}

public struct QueryResponseAutoContinue {
    public let `cursor`: String
    public let `policy`: AutoContinuePolicy
    public let `retry`: AutoContinueRetry?
}

public struct QueryResponseExtensionCatalog {
    public let `craft_id`: String
    public let `harness`: String
    public let `native_metadata`: String
}

public struct QueryResponseExtensionChange {
    public let `action`: ExtensionAction
    public let `change_id`: String
    public let `craft_id`: String
    public let `extension_id`: String
    public let `state`: ExtensionChangeState
}

public struct QueryResponseRemoteToolReview {
    public let `action`: RemoteToolAction
    public let `destination_plane_id`: String
    public let `operation_id`: String
    public let `origin`: NoVisaOrigin
    public let `permissions`: [BrokerPermission]
    public let `workspace_id`: String
}

public struct QueryResponseUtility {
    public let `binding_id`: String?
    public let `job_id`: String
    public let `model`: String?
    public let `outcome`: UtilityOutcome
    public let `plane_id`: String
    public let `policy`: UtilityPolicy
    public let `provider`: String?
    public let `purpose`: UtilityPurpose
}

public struct QueryResponseCraftInstallationPreview {
    public let `confirmation`: CraftInstallationConfirmation
    public let `craft_id`: String
    public let `enabled_features`: [String]
    public let `version`: String
}

public struct QueryResponseScheduledTasks {
    public let `cursor`: String
    public let `tasks`: [ScheduledTask]
}

public struct QueryResponseEditableFile {
    public let `content`: String?
    public let `cursor`: String
    public let `path`: String
    public let `revision`: FileRevision
    public let `target`: FileTarget
}

public struct QueryResponseWorkspaceTerminals {
    public let `cursor`: String
    public let `terminals`: [WorkspaceTerminal]
}

public struct QueryResponseChangeArtifact {
    public let `artifact`: ChangeArtifact
    public let `bytes`: [Int64]
    public let `offset`: String
}

public struct QueryResponseChangeDiff {
    public let `after`: ChangeSnapshot
    public let `artifact`: ChangeArtifact
    public let `before`: ChangeSnapshot
    public let `cursor`: String
    public let `files`: [ChangedFile]
    public let `latest_turn`: UInt32
    public let `next_page`: PageCursor?
    public let `outcome`: TurnOutcome?
    public let `patch`: String
    public let `patch_truncated`: Bool
    public let `plane_id`: String
    public let `run_id`: String
    public let `scope`: DiffScope
    public let `total_files`: UInt32
    public let `workspace_id`: String?
}

public struct QueryResponseTurnQueue {
    public let `cursor`: String
    public let `turns`: [Turn]
}

public struct QueryResponseOrphanedExecutions {
    public let `executions`: [OrphanedExecution]
    public let `next`: String?
}

public struct QueryResponseRunExecution {
    public let `activity`: RunActivity?
    public let `cursor`: String
    public let `exit_code`: Int32?
    public let `native_conversation`: String?
    public let `needs_attention`: Bool?
    public let `no_visa`: NoVisaSelection?
    public let `processes`: [ManagedProcess]
    public let `run`: Run
    public let `termination`: RunTermination?
    public let `visa`: VisaSelection?
}

public struct QueryResponseStatus {
    public let `core_version`: String
    public let `cursor`: String?
    public let `daemon_starts`: UInt64
    public let `plane_id`: String
    public let `security`: SecurityState?
    public let `started_at_unix_ms`: Int64
}

public struct QueryResponseConversations {
    public let `conversations`: [Conversation]
    public let `cursor`: String
    public let `next_page`: PageCursor?
}

public struct QueryResponseConversation {
    public let `conversation`: Conversation
    public let `cursor`: String
    public let `runs`: [Run]
    public let `workspace`: Workspace?
}

public struct QueryResponseCapabilities {
    public let `core_version`: String
    public let `crafts`: [InstalledCraft]
    public let `credential_store`: CredentialStoreStatus
    public let `degraded`: [DegradedCondition]
    public let `external_tools`: [ExternalToolStatus]
    public let `harnesses`: [String]
    public let `observed_at_unix_ms`: Int64
    public let `platform`: Platform
    public let `resource_budgets`: ResourceBudgets?
}

public struct QueryResponseAccountBindings {
    public let `bindings`: [AccountBindingStatus]
    public let `cursor`: String
}

public struct QueryResponseUsage {
    public let `consumption`: ObservedConsumption
    public let `cursor`: String
    public let `plane_id`: String
    public let `quota_windows`: [QuotaWindow]
}

public struct QueryResponseSettings {
    public let `cursor`: String
    public let `scope`: SettingScope
    public let `settings`: [ResolvedSetting]
}

public struct QueryResponseEvents {
    public let `cursor`: String
    public let `events`: [Event]
}

public struct QueryResponsePairing {
    public let `clients`: [PairedClient]?
    public let `cursor`: String
    public let `gate`: PairingGate
    public let `pending`: PendingPairing?
}

public struct QueryResponseSecurityAudit {
    public let `cursor`: String
    public let `entries`: [AuditEntry]
}

public struct QueryResponseProjects {
    public let `cursor`: String
    public let `projects`: [Project]
}

public struct QueryResponseProjectPreview {
    public let `registrability`: Registrability
    public let `root`: String
}

public struct QueryResponseProjectEntry {
    public let `cursor`: String
    public let `kind`: EntryKind
    public let `path`: String
    public let `project_id`: String
}

public struct QueryResponsePromotionPreview {
    public let `binding`: PromotionBinding
    public let `changed_paths`: UInt32
    public let `changes`: [PromotedChange]
    public let `cursor`: String
}

public struct QueryResponseSearch {
    public let `cursor`: String
    public let `hits`: [SearchHit]
    public let `indexed_through`: String
}

public struct QueryResponseExternalConversations {
    public let `cursor`: String
    public let `discovered`: [ExternalConversation]
    public let `imported`: [ImportedConversation]
}

public struct QuotaScopeProviderAccount {

}

public struct QuotaScopeModel {
    public let `model`: String
}

public struct RecoveryActionRefreshFile {
    public let `current_revision`: FileRevision
    public let `path`: String
    public let `target`: FileTarget
}

public struct RecoveryActionRefreshConversation {
    public let `conversation_id`: String
}

public struct RecoveryActionRefreshRun {
    public let `run_id`: String
}

public struct RecoveryActionResumeEvents {
    public let `after`: String
}

public struct RegistrabilityRegistrable {
    public let `repository`: Repository
}

public struct RegistrabilityNotARepository {

}

public struct RegistrabilityBrokenRepository {

}

public struct RegistrabilityBareRepository {

}

public struct RegistrabilityInsideGitDir {

}

public struct RegistrabilityInsideWorkingTree {
    public let `toplevel`: String
}

public struct RemotePairingRequestClaim {
    public let `command_id`: String
    public let `key`: ClientPublicKey
    public let `secret`: String
}

public struct RemotePairingRequestComplete {
    public let `command_id`: String
    public let `offer_id`: String
    public let `signature`: String
}

public struct RemotePairingResponseClaimed {
    public let `pending`: PendingPairing
    public let `signing_bytes`: [Int64]
}

public struct RemotePairingResponseCompleted {
    public let `client`: PairedClient
}

public struct RemotePairingResponseRejected {
    public let `error`: WireError
}

public struct RemoteToolActionTerminal {
    public let `columns`: Int64
    public let `directory`: String
    public let `input`: String
    public let `rows`: Int64
}

public struct RemoteToolActionProcess {
    public let `arguments`: [String]
    public let `directory`: String
    public let `environment`: [RemoteEnvironment]
}

public struct RemoteToolActionGit {
    public let `operation`: RemoteGitOperation
}

public struct RemoteToolActionShell {
    public let `directory`: String
    public let `environment`: [RemoteEnvironment]
    public let `script`: String
}

public struct RemoteToolActionWriteFile {
    public let `content`: String
    public let `path`: String
}

public struct RemoteToolActionReadFile {
    public let `path`: String
}

public struct RemoteToolResultApprovalRequired {
    public let `operation_id`: String
}

public struct RemoteToolResultProcess {
    public let `exit_code`: Int32?
    public let `stderr`: String
    public let `stdout`: String
}

public struct RemoteToolResultWritten {

}

public struct RemoteToolResultFile {
    public let `content`: String
}

public struct RestartMetadataCursorExpired {
    public let `current_snapshot_revision`: String
    public let `minimum_available_cursor`: String
}

public struct RestartMetadataCursorAhead {
    public let `current_snapshot_revision`: String
}

public struct RestartMetadataPaginationStale {
    public let `current_snapshot_revision`: String
}

public struct SecurityStateTrusted {

}

public struct SecurityStateDegraded {
    public let `breach`: AuditBreach
    public let `epoch`: String
    public let `head`: AuditHead?
    public let `store_sequence`: String
}

public struct SeedSelectionNone {

}

public struct SeedSelectionAllEligible {

}

public struct SeedSelectionPaths {
    public let `paths`: [String]
}

public struct ServerHelloChallenge {
    public let `nonce`: String
}

public struct ServerHelloWelcome {
    public let `capabilities`: [String]?
    public let `codec`: String
    public let `max_control_frame`: UInt32
    public let `max_data_frame`: UInt32
    public let `minor`: UInt32
    public let `protocol`: UInt32
}

public struct ServerHelloRejected {
    public let `error`: WireError
}

public struct ServerMessageRemoteToolResult {
    public let `id`: UInt64
    public let `result`: RemoteToolResult
}

public struct ServerMessageTerminalAttached {
    public let `id`: UInt64
}

public struct ServerMessageTerminalResized {
    public let `id`: UInt64
}

public struct ServerMessageQueryResult {
    public let `id`: UInt64
    public let `result`: QueryResponse
}

public struct ServerMessageCommandResult {
    public let `id`: UInt64
    public let `result`: CommandResponse
}

public struct ServerMessageError {
    public let `error`: WireError
    public let `id`: UInt64?
}

public struct SettingScopePlane {

}

public struct SettingScopeProject {
    public let `project_id`: String
}

public struct SettingScopeConversation {
    public let `conversation_id`: String
}

public struct SettingSelectionAll {

}

public struct SettingSelectionKey {
    public let `key`: SettingKey
}

public struct SettingSourceBuiltIn {

}

public struct SettingSourceScope {
    public let `scope`: SettingScope
}

public struct SettingValueFlag {
    public let `value`: Bool
}

public struct SettingValueText {
    public let `value`: String
}

public struct SettingValueCount {
    public let `value`: UInt32
}

public struct StreamControlCredit {
    public let `bytes`: UInt64
}

public struct StreamControlTerminalGap {
    public let `first_missing_offset`: String
    public let `missing_bytes`: String
}

public struct StreamControlTerminalFinished {
    public let `total_bytes`: String
}

public struct StreamControlArtifactFinished {
    public let `sha256`: Sha256Digest
    public let `total_bytes`: String
}

public struct ToolAvailabilityPresent {
    public let `version`: String
}

public struct ToolAvailabilityMissing {

}

public struct UsageFreshnessFresh {

}

public struct UsageFreshnessStale {

}

public struct UsageFreshnessUnreachable {
    public let `reason`: String
}

public struct UsageSelectionPlane {

}

public struct UsageSelectionBinding {
    public let `binding_id`: String
}

public struct UsageSelectionConversation {
    public let `conversation_id`: String
}

public struct UsageSelectionRun {
    public let `run_id`: String
}

public struct UtilityOutcomePending {

}

public struct UtilityOutcomeDraft {
    public let `inactive_days`: UInt32
}

public struct UtilityOutcomeText {
    public let `body`: String
    public let `fallback_reason`: String?
    public let `text`: String
}

public struct UtilityOutcomeRefused {
    public let `reason`: String
}

public struct UtilityRequestNaming {
    public let `run_id`: String
}

public struct UtilityRequestGitText {
    public let `run_id`: String
    public let `turn`: UInt32
}

public struct UtilityRequestAutodelete {
    public let `prompt`: String
}

public struct WorkingTreeNoProject {

}

public struct WorkingTreeWorkspace {
    public let `project_id`: String
}

public struct WorkingTreeLocalCheckout {
    public let `project_id`: String
}

public struct WorkingTreeRequestNoProject {

}

public struct WorkingTreeRequestWorkspace {
    public let `base`: BaseSelection?
    public let `project_id`: String
    public let `seed`: SeedSelection?
}

public struct WorkingTreeRequestLocalCheckout {
    public let `project_id`: String
}

public struct WorktreeMain {

}

public struct WorktreeLinked {
    public let `common_dir`: String
}
